### ISSUE TITLE
Remove blank space on entry page (mobile version)

### ISSUE THREAD

**Issue by yandriiv** [ita-social-projects/ZeroWaste#324]
Expected result: 
No blank space under the main section on entry page.
 
Actual result:
Blank space is presence under the main section on entry page (image below).

![Image](https://user-images.githubusercontent.com/123062069/216370249-0b2fe3d0-18a3-43ee-9301-030839584521.png)

**Comment by AndriyAndriyovuch** [comment]
Issue isn't actual no more

![Знімок екрану з 2023-09-17 12-16-19](https://github.com/ita-social-projects/ZeroWaste/assets/95449986/c9da6f03-36aa-4f68-bdf2-d00caed2378b)
