### ISSUE TITLE
center placing of the button "How to use less"

### ISSUE THREAD

**Issue by yandriiv** [ita-social-projects/ZeroWaste#330]
Expected result:
In web version the button "How to use less" is centered by height (the same as placing of the button "Як зменшити використання" for UA version ).

Actual result: 
In web version the button "How to use less" is not centered (see screenshot below). 

![Image](https://user-images.githubusercontent.com/123062069/218401889-a7ddd96d-ac79-4729-9249-b32d1fccf5e2.png)

**Comment by AndriyAndriyovuch** [comment]
![Знімок екрану з 2023-11-10 16-27-33](https://github.com/ita-social-projects/ZeroWaste/assets/95449986/3fe67fc7-f88e-46cc-86ea-6261999b2dbf)
