### ISSUE TITLE
correct the algorithm of drop-down lists for years and months

### ISSUE THREAD

**Issue by yandriiv** [ita-social-projects/ZeroWaste#332]
Expected result:
The last chosen months should be saved or dropped.

Actual result:
The months are changing when switching between years (for example: 2 years -> 1 year). See the video attached.

https://user-images.githubusercontent.com/123062069/218409625-e89578f7-b2b0-4b5b-b19a-b485dcea8821.mp4

**Comment by loqimean** [comment]
doubtful task

**Comment by AndriyAndriyovuch** [comment]
Issue isn't actual no more

[Запис екрану від 17.09.23 12:20:54.webm](https://github.com/ita-social-projects/ZeroWaste/assets/95449986/5a0b5695-e3e8-4e8d-95f9-f454e08fbc36)
