### ISSUE TITLE
correct data format for icons

### ISSUE THREAD

**Issue by yandriiv** [ita-social-projects/ZeroWaste#351]
Expected result:
When years and months are chosen, the values for icons 'UAH already spent on diapers' and 'UAH yet to be spent on diapers' are rounded (one digit after comma).

Actual result:
Values for icons 'UAH already spent on diapers' and 'UAH yet to be spent on diapers' are not rounded (see screenshot).

![Image](https://user-images.githubusercontent.com/123062069/220050423-3f37d5e6-d60c-4a29-9266-be483bde73ec.png)

**Comment by AndriyAndriyovuch** [comment]
already rounded and deployed
