### ISSUE TITLE
As an admin user, I want to have the ability to modify the site settings, including the option to enable "Access Admin Menu" and update the site name, with the ability to save my changes.

### ISSUE THREAD

**Issue by VolodymyrTurchyn** [ita-social-projects/ZeroWaste#428]
As an admin user, 
I want to have the ability to modify the site settings, including the option to enable the "Access Admin Menu" 
and update the site name, with the ability to save my changes.

Acceptance Criteria:

1. In the site settings section, there should be an option labeled "Access Admin Menu" with a corresponding checkbox.
2. Checking the "Access Admin Menu" checkbox should grant access to the admin menu for the logged-in admin user who checked that checkbox.
3. Unchecking the "Access Admin Menu" checkbox should revoke access to the admin menu for the logged-in admin user who checked that checkbox.
4. The change in the "Access Admin Menu" option should take effect immediately after pressing "Save" button and without requiring a page refresh.
5. In the site settings, there should be a field labeled "Site Name" where the admin user can enter a new name for the website.
6. The "Site Name" field should have appropriate validation to ensure it is not left blank and meets length (from 3 to 30 characters) and formatting requirements (letters, numbers and special characters).
7. After entering a new site name, the website should update its displayed name to reflect the changes made by the admin user.
8. The changes made to the "Access Admin Menu" and "Site Name" should persist even after the admin user logs out and logs back in.
9. There should be a save button or a similar mechanism to allow the admin user to save their changes in the site settings.
10. Clicking the save button should validate the form inputs and apply the changes to the "Access Admin Menu" and "Site Name" settings.
11. After successfully saving the changes, the admin user should receive a confirmation message or notification indicating that the changes have been saved.

**Comment by kikimou** [comment]
Not relevant anymore
