### ISSUE TITLE
[Waiting for stakeholders answer] Length requirement for the "Site name" field

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/ZeroWaste#433]
- Are lenght or formatting requirements in another US?
	OR
- Should we set lenght requirement to 16 or 24 or 32 characters?

**Comment by kikimou** [comment]
Paragraph 6 in US #428

**Comment by kikimou** [comment]
Answer: waiting for actions from another team

**Comment by onakone** [comment]
The title length should be from 3 to 30, agreed with tech lead Ivan Marynych
