### ISSUE TITLE
[Waiting for stakeholders answer] The "Site name" field should allow

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/ZeroWaste#434]
The "Site name" field should allow:
ㅤ- Only letters
ㅤ- Letters and numbers
ㅤ- Letters, numbers and special characters 
ㅤㅤ- if with special characters then what's the full character selection?
ㅤㅤㅤ- Unicode or ASCII or Custom section?

**Comment by kikimou** [comment]
Answer: TBD

**Comment by onakone** [comment]
The "Site name" field should allow:
ㅤ- Only letters
ㅤ- Letters and numbers
ㅤ- Letters, numbers and special characters
ㅤㅤ- if with special characters then what's the full character selection?
ㅤㅤㅤ- Unicode or ASCII or Custom section?

there are no specific restrictions, all the above-mentioned things should be allowed.
