### ISSUE TITLE
Clarification on US #424

### ISSUE THREAD

**Issue by natalka-v** [ita-social-projects/ZeroWaste#442]
Dear Mr. Oleh
In User Story 424:
[As an admin user, I want to be able to use the products section of the website with the ability to add new products or rename existing ones.#424]

The fourth acceptance criterion below requires the “Create” and “Cancel” buttons to be the same size. Is there a mockup that will give an unequivocal answer to the question of what size buttons are needed?

4. The "Create" and "Cancel" buttons should have the same size, creating a visually consistent interface

I am waiting for a reply. Thank you

**Comment by AndriyAndriyovuch** [comment]
Size was fixed 

![Знімок екрану з 2023-11-11 14-35-44](https://github.com/ita-social-projects/ZeroWaste/assets/95449986/c2e0f9fd-3cc5-4f56-9447-194a5e723536)
