### ISSUE TITLE
Wrong error message on page Product when user try to create product without title

### ISSUE THREAD

**Issue by VolodymyrTurchyn** [ita-social-projects/ZeroWaste#454]
Windows 10, Google chrome 114.0.5735.199

Steps to Reproduce:
1) Go to https://zero-waste-staging.onrender.com/en/account/products
2) Click button "Add Product"

3) Put nothing in field "Title" and click button  "Create"

Expected Result :
Error message that Title is required

Actual Result:
Error message: The change you wanted was rejected. Maybe you tried to change something you didn't have access to.

![Image](https://github.com/ita-social-projects/ZeroWaste/assets/138515990/4e0dceab-51d5-46a0-bdd1-44f2d5a8e22a)

**Comment by AndriyAndriyovuch** [comment]
already done and deployed
