### ISSUE TITLE
Absence of picture on the site in the section About us/History when switching the language on the site

### ISSUE THREAD

**Issue by VolodymyrTurchyn** [ita-social-projects/ZeroWaste#456]
Windows 10, Google chrome 114.0.5735.199

Steps to Reproduce:

Go to https://zerowastelviv.org.ua/pro-zero-waste-lviv/

Click button of changing of language from Ukrainian to English in top right corner

Expected Result :
Pictures are on the same place

Actual Result:
Page doesn't have enough pictures

![Image](https://github.com/ita-social-projects/ZeroWaste/assets/138515990/51ab676a-c362-4bee-b095-be558ff5a2f8)
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/138515990/f757bbb5-71e8-45eb-bde1-a75b97ae74f5)

**Comment by AndriyAndriyovuch** [comment]
doesn't belong to this project
