### ISSUE TITLE
On the site settings possibility to click on the button "Choose File" goes beyond the button

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/ZeroWaste#467]
**Steps to Reproduce:**
1. Log in to the site as an Admin
2. Go to [Site Settings](https://zero-waste-staging.onrender.com/en/account/site_setting/edit)
3. Click on any empty space to the right of the button "Choose File"

**Expected Result:**
Nothing should happen

**Actual Result:**
Folder for choosing the favicon opens

**Visual representation of the defect:**
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/83531484/3cd2e28c-5ed7-4da1-a985-37f252c7448c)

**Comment by kikimou** [comment]
What is missing and what requirements?

**Comment by glckfndr** [comment]
Скріншот зроблено неправильно

**Comment by glckfndr** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/24854291/d6b60f9e-0978-4753-8cb2-2f62ea2587b7)

**Comment by glckfndr** [comment]
Я користуюсь  Lightshot для скріншотів. Дуже зручно.

**Comment by glckfndr** [comment]
Оформіть так, як написано на цьому сайті
https://training.qatestlab.com/blog/course-materials/results-bug-report/

**Comment by loqimean** [comment]
та нормальний скріншот

**Comment by loqimean** [comment]
і взагалі лайтшот не секюрний, сподіваюся ніукого його не побачу

**Comment by loqimean** [comment]
коменти

**Comment by NatLabyk** [comment]
Fixed
