### ISSUE TITLE
On the Site Setting the system redirects to non-existing page after uploading a valid favicon file and pressing an "Update" button

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/ZeroWaste#473]
Steps to reprtoduce:
1. Log in to the site as an Admin
2. Go to [Site Settings](https://zero-waste-staging.onrender.com/en/account/site_setting/edit)
3. Upload a valid favicon file (you can [take this](https://user-images.githubusercontent.com/83531484/252947805-26595591-566c-4cf2-a099-ead735100f7f.png))
4. Press the "Update" button

Actual Result:
Redirect to non-existing page

Expected Result:
Message in the header "Setting was successfully updated" on the Site Settings page without any redirections

**Comment by obniavko** [comment]
Message in the header "Settings were successfully updated" on the Site Settings page is shown as intended, **but only locally.**
Suggestion: Possible issues with the Render hosting platform?

![Image](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/f1846ddc-64fb-4b9a-ae60-e1954c7ab386)

**Comment by obniavko** [comment]
Bug was fixed.
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/e8418eaa-b528-4d07-8f45-4b061f458268)
