### ISSUE TITLE
[Answer from BA needed] Validation errors for favicon (size, type, resolution)

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/ZeroWaste#474]
Validation errors for file size limit exceeding:
- File size limit is 1KB
- Favicon file too large, please upload file up to 1KB
- Favicon file exceeds maximum size of 1KB

Validation errors for wrong file format:
- Only .PNG and .ICO file formats are allowed for favicons
- Please upload a favicon in .PNG or .ICO file format
- Please ensure that your favicon file is .PNG or .ICO format and try again.

Validation errors for wrong resolution:
- Favicon resolution must be a multiple of square (for example: 16x16px)
- Please resize your favicon to a resolution that is a multiple of square (e.g. 16x16px)
- Favicon dimensions must be a multiple of in both width and height (16x16px, 32x32px and so on)

**Comment by onakone** [comment]
I suggest the next options

Validation errors for file size limit exceeding:

- Favicon file too large, please upload file up to 1KB

Validation errors for wrong file format:

- Only .PNG and .ICO file formats are allowed for favicons

Validation errors for wrong resolution:

- Favicon resolution must be a multiple of square (for example: 16x16px)
