### ISSUE TITLE
Is it necessary to have 2 confirmation buttons on the site settings page?

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/ZeroWaste#475]
Currenty we have 2 confirmation of changes buttons:
- "Update" - confirms changes of Title and Favicon
- "Save" - confirms changes of "Name" checkbox (access admin menu checkbox was removed)

Is it appropriate to have 1 speacial confirmation button for a single checkbox?

**Comment by kikimou** [comment]
Answer: yes

**Comment by loqimean** [comment]
so, it's different interfaces that should be divided by two pages or two different forms (with two submit (or update) buttons) for certain functionality
