### ISSUE TITLE
On sites buttons "Create" and "Cancel" has different size

### ISSUE THREAD

**Issue by Vrkoval** [ita-social-projects/ZeroWaste#486]
Precondition: Verifiy size of buttons "Create" and "Cancel"

Steps to Reproduce:

1. Log in to the site like admin user.
2. In admin menu order "Categories/Категорії"
3. Click button "+Add category/+Додати категорію"

Expected Result:
"Create" and "Cancel" buttons should have the same size, and their text should be centered.

Actual Result:
"Create" and "Cancel" buttons shouldn't have the same size, and their text shouldn't be centered.

![Image](https://github.com/ita-social-projects/ZeroWaste/assets/118452709/151a3cb1-816b-4208-a622-1368509daf57)
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/118452709/2d575933-62f7-494f-9b90-9740db195490)

E.g.: "User story #427

**Comment by AndriyAndriyovuch** [comment]
Already deployed

![Знімок екрану з 2023-11-10 16-33-34](https://github.com/ita-social-projects/ZeroWaste/assets/95449986/566a33f4-a78e-4404-9eec-d4fe94b3247f)
