### ISSUE TITLE
Resolution limit for uploading allowed files to favicon

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/ZeroWaste#494]
As US #426 paragraph 3 says the image file should have a multiple of 48px square, for example: 48x48px, 96x96px, 144x144px and so on.

So the minimal resolution is 48x48px.

But what's the maximal (limit)?
 - Should we use 48*5 = 240x240px
 OR
 - Should we use 48*10 = 480x480px

**Comment by loqimean** [comment]
Browser favicons - 16x16
Taskbar shortcut icons – 32x32
Desktop shortcut icons – 96x96
Apple touch icons – 180x180
