### ISSUE TITLE
[Answer from the stakeholders needed] How the revert to the default favicon and title button should be named?

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/ZeroWaste#495]
As US #426 paragraph 9 says we should have a button for the admin user to revert to the default favicon and title if desired.

In the last meeting we had a dispute how the revert button should be named "Cancel", "Reset" or "Revert" and came to the conclusion that we should ask the client.

**Comment by onakone** [comment]
as it was discussed on our sync 19.07 we can close this clarification as N.A.
