### ISSUE TITLE
There are two overlapping messages below the category name field on the category page

### ISSUE THREAD

**Issue by natalka-v** [ita-social-projects/ZeroWaste#508]
Steps to Reproduce:

1. Log in to the site as an Admin
2. Go to https://zero-waste-staging.onrender.com/en/account/categories/new?id=%23%3CCategory%3A%3AActiveRecord_Relation%3A0x0000557a37d74270%3E
3. Leave the category name input field blank
4. Click the Create button

Actual Result:
Messages overlap each other

Expected Result:
Messages do not overlap

**Comment by natalka-v** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/130998282/40b79335-0d36-400e-8103-578a4fcbef36)

**Comment by iambrozjak** [comment]
The message "Please, fill owt this field" is generated by the browser, according to its documentation, and not by our application. Therefore, there is no point in fixing this bug. So this task is closed (agreed with the technical expert).
