### ISSUE TITLE
Allowed size, resolution and type of file for Favicon on the Site Settings page

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/ZeroWaste#511]
As clarified with TL favicon on the Site Settings page should allow files:

- With size up to 1kb
- With resolution up to 180x180 (always should be a multiple of square)
- With file type .png or .ico

Source:
![Image](https://user-images.githubusercontent.com/83531484/255322755-479cb2f1-8acb-4426-be63-64e0d7fa5619.png)

**Comment by kikimou** [comment]
Link to story #426, paragraph 3

**Comment by DmytroStoliaruk** [comment]
In the current version type and size of file for Favicon is validate with error messages.
