### ISSUE TITLE
Validation errors for favicon on the Site Settings page

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/ZeroWaste#512]
As clarified with BA, the following errors should be shown if the conditions for the uploaded favicon file are not met.

Size: Favicon file too large, please upload file up to 1KB
Resolution: Favicon resolution must be a multiple of square (for example: 16x16px)
Type: Only .PNG and .ICO file formats are allowed for favicons

The user has to see all the errors for all the mistakes he has made.

Sources: 
https://github.com/ita-social-projects/ZeroWaste/issues/474#issuecomment-1642585667

![Image](https://github.com/ita-social-projects/ZeroWaste/assets/83531484/2bb6cb41-0eb6-4c2d-bed1-ee79ef67eb2a)

**Comment by DmytroStoliaruk** [comment]
It looks as [ZeroWaste #511](https://github.com/orgs/ita-social-projects/projects/25?pane=issue&itemId=33934729).

**Comment by NatLabyk** [comment]
The same like #511 . Done

![Image](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/ca4c6d0d-8df6-4ad1-926e-7e6ff32ec10a)
