### ISSUE TITLE
Confirmation message of successful changes after pressing the Revert button

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/ZeroWaste#516]
After user have pressed "Revert" button the title and favicon are reverted to their defaults, so there should be a message of successful changes. We propose the following:

- The title and favicon have been successfully reverted to their default state.
- The title and favicon have been reset to their original defaults.
- The title and favicon settings have been reverted to default.
- Title and favicon are now set to default.

**Comment by AndriyAndriyovuch** [comment]
Done in https://github.com/ita-social-projects/ZeroWaste/pull/545

uk: "Заголовок і піктограму сайту успішно відновлено до стандартних"
en: "The title and favicon have been successfully reverted to default"
