### ISSUE TITLE
Verification of the Title text field on site settings task for lenght and formatting requirements at Zero Waste site.

### ISSUE THREAD

**Issue by Andriyua7** [ita-social-projects/ZeroWaste#517]
Negative test case.

Invalid data is entered and the update button is pressed, an error message should be displayed and the entered invalid data should not be saved.

Preconditions:
1. User is Logged in as admin on the Zero Waste site.
2. The site setings is open.

Step to reproduse.

Input in text field more than 30 character. Click update button.

Test data.

1. Any characters more than 30.
2. 31.

Expected result.

Error message: Title is too long (maximum is 30 characters).

Actual result.

Error  message: Title is too long (maximum is 20 characters).

**Comment by Andriyua7** [comment]
Step to reproduse.

Input in text field more than 30 character. Click update button.

Test data.

1. Any characters more than 30.
2. 31.

Expected result.

Error message: Title is too long (maximum is 30 characters).

Actual result.

Error  message: Title is too long (maximum is 20 characters).

**Comment by AndriyAndriyovuch** [comment]
Duplicated issue, already done in https://github.com/ita-social-projects/ZeroWaste/issues/493
