### ISSUE TITLE
[Site Settings page] Favicon lasts for ~20 min after uploading, then dissapears

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/ZeroWaste#532]
**Steps to reprtoduce:**

1. Log in to the site as an Admin
2. Go to [Site Settings](https://zero-waste-staging.onrender.com/en/account/site_setting/edit)
3. Upload a valid favicon file (you can [take this](https://user-images.githubusercontent.com/83531484/252947805-26595591-566c-4cf2-a099-ead735100f7f.png))
5. Press the "Update" button

**Expected Result:**
Changes to favicon should persist until admin user upload new it or press Revert button

**Actual Result:**
22 min later favicon is gone

![Image](https://user-images.githubusercontent.com/83531484/256212723-9c82350c-55e1-4c6a-8721-b7bed3cfe7e4.png)
![Image](https://user-images.githubusercontent.com/83531484/256212745-a100a3c3-d0fd-4fa1-85be-8aa7f04fbdce.png)

**Comment by obniavko** [comment]
I uploaded a [favicon file](https://zerowastelviv.org.ua/wp-content/uploads/2021/03/cropped-logo-zerowaste-lv-04-32x32.png) 1 hour ago and it still persists. Opened website on desktop and mobile, the favicon is displayed correctly. It seems that the issue is no longer relevant.

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/e50b1c01-f7f9-4d92-80da-b1941829d9b7)
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/04d9a419-b049-4976-ab16-2bd2e7760760)

Done

**Comment by fh0enix** [comment]
**### RETEST PLEASE**

**Comment by AShoshu** [comment]
![4](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/e6b4fea8-574f-4219-b928-7ca5fac6e032)
![Снимок экрана 2024-01-17 084846](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/d96e8324-a366-4104-9034-9b4eac5bdc93)
