### ISSUE TITLE
[Calculator Page] Changing the price category without changing the child's age does not allow to get new calculation results

### ISSUE THREAD

**Issue by obniavko** [ita-social-projects/ZeroWaste#556]
**Steps to reproduce:**

1. Choose the _Child's age_ and the _Price category_. Press the "Calculate" button.
2. Change the _Price category_ without changing the _Child's age_. Press the "Calculate" button again.

**Expected Result:**
New calculation results are displayed.

**Actual Result:**
After changing the _Price category_ (without changing the _Child's age_), the "Calculate" button is inactive, you must change the _Child's age_ to get the results.

![Image](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/bd46813a-a92f-4f52-bee9-bdd92be95944)

To do list

- [x] create a new model to store periods of a child's life, the diaper consumption per day, and the price per unit that will belong to one of the categories.
- [x] validations for the model
- [x] validation to check the overlap period
- [x] rework calculations based on new possible categories
- [x] number of categories can be arbitrary
- [x] number of periods can be arbitrary
- [x] after adding periods to a category, the category becomes available for calculations
- [x] on the New Design Calculator page, display all categories that have a diaper periods
- [x] cover the functionality with tests

**Comment by NatLabyk** [comment]
Done
