### ISSUE TITLE
[Site Settings page] Wrong error message in Site Settings for files more than 500K

### ISSUE THREAD

**Issue by DmytroStoliaruk** [ita-social-projects/ZeroWaste#558]
Wrong error message in Site Settings view if Admin chose as a Favicon file  more than 500K

Steps to reproduce:

1. Go to Admin user to [Site Settings](https://zero-waste-staging.onrender.com/uk/account/site_setting).
2. Chose file as a Favicon whose size is more than 500K
3. Click Apply button.

Expected Result:
Error message: "Favicon has %{file_size} that is not between required range"

Actual Result:
Error message: "Favicon Translation missing: uk.account.site_settings.validations.size"

**Comment by loqimean** [comment]
did you mean more than 500kB?))

**Comment by DmytroStoliaruk** [comment]
Fix issue. The problem was resolved.
