### ISSUE TITLE
Remove duplicate line in the database.yml.sample

### ISSUE THREAD

**Issue by obniavko** [ita-social-projects/ZeroWaste#561]
**Steps to reproduce:**
Open _config/database.yml.sample_ file.

**Expected Result:**
The file contains the pool option on the line 5.

**Actual Result:**
The file contains the duplicate pool option on the line 10.

![ZW](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/e6101f52-9a2b-4415-bdf5-d344b3f253be)

**Comment by NatLabyk** [comment]
Duplicate line is removed
