### ISSUE TITLE
[Flash messages] Flashes do not disappear after clicking on [x]

### ISSUE THREAD

**Issue by dafeys** [ita-social-projects/ZeroWaste#562]
**Steps to reproduce**
Perform any actions that lead to the flash message, for example - log in 

**Actual result**
 Flashes do not disappear after clicking on [x]

**Expected result**
Notifications should disappear after clicking on [x]

Clarification from @loqimean :
[x]  should be at the end of the block with the message

![flash](https://github.com/ita-social-projects/ZeroWaste/assets/36037839/c1fa14c5-254c-452a-94fc-59e9b95c6893)

**Comment by kisiohlova** [comment]
After consulting with the expert @loqimean, was decided to change flash messages to toast notifications.
