### ISSUE TITLE
Delete calculator button does not work on the Calculators page

### ISSUE THREAD

**Issue by Ivaniuk** [ita-social-projects/ZeroWaste#564]
The delete calculator button does not work on the Calculators page in the site admin panel on staging

**Steps to reproduce**
1. Go to https://zero-waste-staging.onrender.com/en/account/calculators
2. Click on Delete icon

**Actual result**
HTTP ERROR 406

**Expected result**
The corresponding calculator must be removed

![remove_button](https://github.com/ita-social-projects/ZeroWaste/assets/34096259/96a2d73a-ade4-4459-a25d-d4cd139cda8a)

**Comment by obniavko** [comment]
**Note:** the View button (eye icon) does not work too. The actual result is _HTTP ERROR 406_.

**Comment by AShoshu** [comment]
Done
