### ISSUE TITLE
[Calculators page] Search button text not visible

### ISSUE THREAD

**Issue by obniavko** [ita-social-projects/ZeroWaste#568]
**Steps to reproduce:**
Open [Calculators page.](https://zero-waste-staging.onrender.com/en/account/calculators)

**Expected Result:**
The text "Search" is visible on the _Search_ button.

**Actual Result:**
The text "Search" is white on the white _Search_ button, and only visible on hover.
![Search](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/11be942f-faff-4e6a-bf92-2bcf35d6c6b8)

**Comment by NatLabyk** [comment]
Defect is fixed
![Search is fixed](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/b985b006-1df5-494a-b163-2eb6a696b116)
