### ISSUE TITLE
[Products page] The product page opens after clicking on the "Delete" button

### ISSUE THREAD

**Issue by obniavko** [ita-social-projects/ZeroWaste#570]
**Steps to reproduce:**
1. Open [Products page](https://zero-waste-staging.onrender.com/en/account/products).
2. Press the "Delete" button (trash icon).

**Expected Result:**
The product is deleted.

**Actual Result:**
The product page is opened.
![ZW-2](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/6ec076cb-bcbf-4604-a260-07323599312f)

**Comment by AShoshu** [comment]
https://github.com/ita-social-projects/ZeroWaste/assets/145554575/51c2decf-75cd-445e-95bd-ee745591f2e9

The "Products" page does not open

**Comment by fh0enix** [comment]
These are not similar problems and require the opening of a separate issue like that https://github.com/ita-social-projects/ZeroWaste/issues/587

**Comment by fh0enix** [comment]
**RETEST PLEASE**
