### ISSUE TITLE
[Setting page] Routing Error if you try to change application language after form error message

### ISSUE THREAD

**Issue by DmytroStoliaruk** [ita-social-projects/ZeroWaste#571]
**Steps to reproduce**
1. Go to '[Site Settings](https://zero-waste-staging.onrender.com/en/account/site_setting/edit)'
2. Set the empty title  
3. Press "Apply" (as a result you will see the error message "Title can't be blank")
4. Try to change the current language [Українська](https://zero-waste-staging.onrender.com/uk/account/site_setting)

**Actual result**
Routing Error 

**Expected result**
Changed menu language

**Comment by AShoshu** [comment]
Step 3:

Actual result:
A confirmation message appeared, "Settings were successfully updated"

Expected result:
 The error message "Title can't be blank"
