### ISSUE TITLE
irrelevant parameters in the URI address

### ISSUE THREAD

**Issue by iambrozjak** [ita-social-projects/ZeroWaste#578]
<img width="687" alt="Bug Zerowaste" src="https://github.com/ita-social-projects/ZeroWaste/assets/129009813/52bd936c-f5ec-4be0-a6d9-e12af5b2d27f">

Steps to Reproduce:
    1. Log in to the site as an Admin
    2. Go to https://zero-waste-staging.onrender.com/en/account/categories
    3. Click the  Add category button
    4.  The address bar contains: https://zero-waste-staging.onrender.com/en/account/categories/new?id=%23%3CCategory%3A%3AActiveRecord_Relation%3A0x00007f08dab32c68%3E), but should contain: 
       [https://zero-waste-staging.onrender.com/en/account/categories/new](https://zero-waste-staging.onrender.com/en/account/categories/new?id=%23%3CCategory%3A%3AActiveRecord_Relation%3A0x00007f08dab32c68%3E)

Actual Result:
[https://zero-waste-staging.onrender.com/en/account/categories/new?id=%23<Category%3A%3AActiveRecord_Relation%3A0x00007f08dab32c68>](https://zero-waste-staging.onrender.com/en/account/categories/new?id=%23%3CCategory%3A%3AActiveRecord_Relation%3A0x00007f08dab32c68%3E)
Expected Result:
[https://zero-waste-staging.onrender.com/en/account/categories/new](https://zero-waste-staging.onrender.com/en/account/categories/new?id=%23%3CCategory%3A%3AActiveRecord_Relation%3A0x00007f08dab32c68%3E)

**Comment by AShoshu** [comment]
Done
