### ISSUE TITLE
Add menu items to the navbar

### ISSUE THREAD

**Issue by obniavko** [ita-social-projects/ZeroWaste#585]
**As a** User **I want to** have links to the _"About us"_, _"Diaper calculator"_/_"Calculators"_ pages in the navigation bar **so that** the website navigation would be more comfortable.

### Acceptance Criteria
The site menu should contain additional menu items such as _"About us"_, and _"Diaper calculator"_/_"Calculators"_ (if the feature flag is enabled) which lead to the corresponding pages.

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/10f4ae8f-2612-4907-ba41-765c69a5c53d)
