### ISSUE TITLE
"[Admin] 'Product' page is not opened after clicking on a 'Product' tab 

### ISSUE THREAD

**Issue by NatLabyk** [ita-social-projects/ZeroWaste#587]
**Environment:** Windows 11 Home Version 22H2 Build	22621.2506
Chrome Версія 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:** ????

**Preconditions**
1. https://zero-waste-staging.onrender.com/uk is opened in browser
2. User is logged in as admin

**Steps to reproduce**
1. Click on 'Admin' tab in header
2. Navigate to 'Product' tab in header of 'Admin' page
3. Click on 'Product' tab

**Actual result**
"We're sorry, but something went wrong. If you are the application owner check the logs for more information." error message is displayed
![Знімок екрана 2023-12-01 153208](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/7606fe0e-974f-41a1-9e8d-bbd346fa1804)

**Expected result**
'Product' page is opened

**User story and test case links**
 "User story #424

**Labels to be added**
"Bug", Priority ("pri: High"), Severity ("severity: Critical"), Type ("Functional").

**Comment by Ytrygub** [comment]
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/68ae9928-a7f3-4603-91bd-d84e38d04cbd)
