### ISSUE TITLE
incorrect display of the button "To main"

### ISSUE THREAD

**Issue by iambrozjak** [ita-social-projects/ZeroWaste#588]
<img width="628" alt="tast to_main" src="https://github.com/ita-social-projects/ZeroWaste/assets/129009813/1470be87-9e6a-4639-bf03-abae94cf957a">
 

Steps to reproduction:
1. Log in to the site
2. Click the "Let's go" button.
4. You will see that the arrow and the text "To main" are placed on different lines and should be on the same line.

Expected result:
The arrow and text are on the same line
ActualExpected result:
The arrow and text are on two lines.

**Comment by NatLabyk** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/e7cff854-22c2-46f4-ae2f-1d0be4d48ef5)

Fixed
