### ISSUE TITLE
Clarification on US #427 Acceptance Criteria #3 Minimum and maximum valid value allowed priority range and field status by default

### ISSUE THREAD

**Issue by AShoshu** [ita-social-projects/ZeroWaste#590]
Dear Mr. Oleg 

In Acceptance Criteria 3 of User Story #427: "The priority range selection should provide clear options, such as a drop-down menu or radio buttons, for the admin user to select the desired range." 

In this point, we should note: 
1. "Priority Range", the minimum and maximum valid value allowed.
 2. This field should be empty by default, or the lowest priority level should be specified by default.

 I am waiting for your answer.
 Sincerely, Anastasia Shoshu.

**Comment by Oksana-Lysak** [comment]
At the meeting on 12/30/2023 with BA Oleh Nakonechniy and Ihor Kohut decided to add to Acceptance Criteria 2:
- 'Priority Range' from 0 to 10;
- 0 is the default in the dropdown list
