### ISSUE TITLE
Clarification on US #427 Acceptance criteria 8 Confirmation messages after successfully creating a category

### ISSUE THREAD

**Issue by AShoshu** [ita-social-projects/ZeroWaste#591]
Dear Mr. Oleg
 In Acceptance Criteria 8 of User Story #427 : "After successfully creating a category, the admin user should receive a confirmation message that the category has been added." 

In this point, we suggest clarifying exactly how the administrator user receives the message: 

1. Do we understand correctly that the confirmation message appears on the screen?
2. Can we specify that the text of the message should be: “Category was successfully created”?
3. After successfully creating a category, 'Categories' page is displayed ?

 Waiting for your reply.
 Sincerely, Anastasia Shoshu.

**Comment by Oksana-Lysak** [comment]
At the rally on 12/29/2023 with BA Oleh Nakonechniy and Ihor Kohut confirmed making these changes. They are added to the US.
