### ISSUE TITLE
[Add Category Page]Incorrect  controller in 'Priority' field.

### ISSUE THREAD

**Issue by AShoshu** [ita-social-projects/ZeroWaste#592]
**Environment:** Windows 11.Version 22H2.(64-bit).Firefox 116
**Reproducible:** always
**Build found:** 

**Preconditions**

1. The user is logged into the system as an administrator
2. The "Categories" tab is open

**Steps to reproduce**

1. Click on 'Додати категорію' button.
3. Click on 'Пріоритет' field.

**Actual result**
In the 'Пріоритет' field, a spinner is used to select the priority level

https://github.com/ita-social-projects/ZeroWaste/assets/145554575/ed039968-20b2-4688-9abb-7b5dbe7805b5

**Expected result**
In the 'Пріоритет' field, a drop-down list is used to select the priority level

**User story and test case links**
 "User story #427/ Criteria 3
TC # https://jira.softserve.academy/browse/SWQ-425

**Labels to be added**
"Bug", Priority ("medium"), Severity ("Low"), Type ("UI"),

**Comment by Oksana-Lysak** [comment]
Related issues
https://github.com/ita-social-projects/ZeroWaste/issues/592
https://github.com/ita-social-projects/ZeroWaste/issues/640

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/b71188bc-89be-4ef8-97d7-f4ad3b866c4e)
