### ISSUE TITLE
[Add Category Page]Extra dots at the end in the "Name" field.

### ISSUE THREAD

**Issue by AShoshu** [ita-social-projects/ZeroWaste#593]
**Environment:** Windows 11. Version 22H2.(64-bit). Firefox 116
**Reproducible:** always.
**Build found:**

**Preconditions**

1. User logined in system as Administrator.
2. 'Categories' page is opened.

**Steps to reproduce**
1. Click on 'Add category'

**Actual result**
The field name "Name" contains extra dots at the end
![1](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/27bc2cf0-0157-4aa6-86d4-a9cf373ac985)

**Expected result**
The field name is "Name*".

**User story and test case links**
E.g.: "User story #427 

**Labels to be added**
"Bug", Priority ("low "), Severity ("low"), Type ("UI"),

**Comment by fh0enix** [comment]
this problem was solved and closed for the reason that a similar problem was solved in another case for all similar problems
https://github.com/ita-social-projects/ZeroWaste/issues/615


![Image](https://github.com/ita-social-projects/ZeroWaste/assets/13628239/3e7710a3-7a5b-4f5c-b2b3-501f42f65a9c)

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/7cd87f3e-bb58-4fa3-8179-04c8f2fe1861)

done
