### ISSUE TITLE
[Site Setting Page] Wrong font, size, color and localization of UI controls

### ISSUE THREAD

**Issue by Vadym123456** [ita-social-projects/ZeroWaste#595]
**Environment:** Windows 10 Home, Google Chrome Version 119.0.6045.200 (Official Build) (64-bit)
**Reproducible:** always
**Build found:**

**Preconditions**
1. The user is logged into the system as an Administrator.
2. The 'Site Settings' page is opened.

**Steps to reproduce**
1. Verify that the 'Save' and 'Revert' buttons are are in the right place on the page.
2. Verify the font, size, and color of these buttons.

**Actual result** 

1. The 'Revert' button is in the bottom right corner
2. The 'Revert' button color is red
3. The 'Revert' button label is black
4. The 'Revert' button is too small

![1](https://github.com/ita-social-projects/ZeroWaste/assets/152202833/b14ed50f-e0b5-4991-897b-55419e256602)

**Expected result**

1. 'Revert' button is next to 'Save' button
2. 'Revert' button color is grey
3. 'Revert' button lable is white
4. 'Revert' Button is the same size as 'Save' button

![2](https://github.com/ita-social-projects/ZeroWaste/assets/152202833/97404c33-5f2b-44ca-995f-64c10687a437)

**User story and test case links**
"User story #426 
TC https://jira.softserve.academy/projects/SWQ?selectedItem=com.thed.zephyr.je%3Azephyr-tests-page#test-cycles-tab

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI")

**Comment by AShoshu** [comment]
![4](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/058bd1a8-8d31-4ccf-921c-3a06e37ea404)
Done
