### ISSUE TITLE
[Sign up page] The default value for the country is not "Ukraine"

### ISSUE THREAD

**Issue by obniavko** [ita-social-projects/ZeroWaste#599]
**Steps to reproduce:**
1. Open [Sign up page.](https://zero-waste-staging.onrender.com/en/users/sign_up)

**Expected Result:**
The default value for the country in the sign-up form is "Ukraine" (since most users are from Ukraine).

**Actual Result:**
The default value for the country in the sign-up form is "Afghanistan" (the first country in the list).

![Country](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/00c1e485-9721-45de-b0bc-8de2f3be3dc7)

**Comment by Ytrygub** [comment]
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/94dae220-66d3-4387-94e3-91c26189f0d1)
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/b367b7b6-94da-4e16-ba44-3a0a653f969e)
