### ISSUE TITLE
[Add Category Page] No error message when creating new Category with empty 'Name' field

### ISSUE THREAD

**Issue by Oksana-Lysak** [ita-social-projects/ZeroWaste#608]
**Environment:** Google Chrome 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:**

**Preconditions**
1. Site is opened in browser: https://zero-waste-staging.onrender.com/uk

2. User is logged in as Administrator

3. 'Categories' page is opened

**Steps to reproduce**
1. Click on 'Add category' button
2. Leave 'Name' field empty
3. Fill in 'Priority' field with valid data: "5"
4. Click on 'Create' button

**Actual result**
Tooltip appears
<img width="958" alt="1" src="https://github.com/ita-social-projects/ZeroWaste/assets/145996520/0b9a732f-3f0c-44fe-b37b-569fa436dfcf">

**Expected result**
Error message appears

**User story and test case links**
"User story #427 

**Labels to be added**
"Bug", Priority ("Low"), Severity ("Low"), Type ("UI")

**Comment by Oksana-Lysak** [comment]
This issue was added to issue 607
https://github.com/ita-social-projects/ZeroWaste/issues/607

**Comment by Oksana-Lysak** [comment]
Related issues
https://github.com/ita-social-projects/ZeroWaste/issues/641

https://github.com/ita-social-projects/ZeroWaste/issues/642

https://github.com/ita-social-projects/ZeroWaste/issues/608

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/5860813b-b010-4fe9-8169-130513bd99ee)
