### ISSUE TITLE
[Add Category Page] Different size of the "Create" and "Cancel" buttons in the ukrainian version of the site

### ISSUE THREAD

**Issue by AnastasiiaBelik** [ita-social-projects/ZeroWaste#610]
![Screenshot 2023-12-03 213410](https://github.com/ita-social-projects/ZeroWaste/assets/145580448/23fad186-912b-4e4c-abf2-2ef4a631825b)
**Environment:** Google Chrome 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found**

**Preconditions:**

 1. Site is opened in browser

 2. User is logged in as Administrator:

 3. 'Categories' page is opened

**Steps to reproduce:**

1. Click on 'Add category' button
2. Select the Ukrainian language for the page
3.  Equalize the size of the "Create" and "Cancel" buttons

**Actual result:**

The sizes of the "Create" and "Cancel" buttons are different

**Expected result:**

The "Create" and "Cancel" buttons are the same size

**User story and test case links**
User story #427 

**Labels to be added**
"Bug", Priority ("Medium "), Severity ("Low"), Type ("UI )

**Comment by Ytrygub** [comment]
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/81d37947-6d26-42bc-88ad-890bcfb17618)
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/8892df48-8505-4cff-ade7-4838fa9b274e)
The buttons size was fixed. Kindly ask you to review the buttons radius. It's different 
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/66cb2fce-68fc-41a9-8e81-596d25a83136)
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/cf3dd2ae-3c3b-4b29-a9cc-21dbe9a88497)

**Comment by Ytrygub** [comment]
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/81344d5c-619f-4957-884e-e397e40203b6)
