### ISSUE TITLE
[Add Category Page] Presence of an icon on the "Cancel" button

### ISSUE THREAD

**Issue by AnastasiiaBelik** [ita-social-projects/ZeroWaste#611]
**Environment:** Google Chrome 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:** 
**Preconditions**
1. User is logged in as Administrator

2. 'Categories' page is opened

**Steps to reproduce**
 1. Click on 'Add category' button
 2. Explore the 'Create' and 'Cancel' buttons

**Actual result**
Buttons of different sizes and an icon present on the "Cancel" button

**Expected result**
Buttons of the same size without unnecessary elements

**User story and test case links**
"User story #427 

**Labels to be added**
"Bug", Priority ("Low"), Severity ("Low"), Type ("UI")
![Screenshot 2023-12-03 213350](https://github.com/ita-social-projects/ZeroWaste/assets/145580448/80fccff6-b59b-44f4-b1d1-e74e4821215e)

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/f57af24e-ca51-44a0-aef7-c3475eb7c980)

Done
