### ISSUE TITLE
[Site Setting Page] Extra dots at the end in the "Title" field in English and in Ukrainian version

### ISSUE THREAD

**Issue by Bozhenaki** [ita-social-projects/ZeroWaste#615]
**Environment:** Windows 11 Home, Google Chrome Version 119.0.6045.200 (Official Build) (64-bit)
**Reproducible:** always
**Build found:**

**Preconditions**

1.User logined in system as Administrator.
2.Go to 'Site setting' Tab.

**Steps to reproduce**
1.Check the field name "Title" in English
2.Check the field name "Назва" in Ukrainian

**Actual result**
The field name "Title" contains extra dots at the end
The field name "Назва" contains extra dots at the end

![bug kropki](https://github.com/ita-social-projects/ZeroWaste/assets/142494049/1b2d2cfb-d58c-49d8-bf15-9f209eac74ca)
![bug kropki2](https://github.com/ita-social-projects/ZeroWaste/assets/142494049/297d7591-538a-4a24-9399-849af412ea9a)

**Expected result**
The field name is "Title*".
The field name "Назва*"

**User story and test case links**
E.g.: "User story #426 

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: low")

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/28754c84-a5e9-4153-9aaa-a5eee835fd48)

done
