### ISSUE TITLE
[Site Setting Page]  incorrect spelling in tooltip in ''Title'' field 

### ISSUE THREAD

**Issue by Bozhenaki** [ita-social-projects/ZeroWaste#616]
**Environment:** Windows 11 Home, Google Chrome Version 119.0.6045.200 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 

**Preconditions**

1.User logined in system as Administrator.
2.Go to 'Site setting' Tab.

**Steps to reproduce**
1.Hover the mouse over the '*' next to 'Title' field

**Actual result**

tooltip: ''required'' (start with small letter)
![required](https://github.com/ita-social-projects/ZeroWaste/assets/142494049/2dace63d-d2b1-497c-8619-3387acc22826)

**Expected result**

tooltip: ''Required'' 

**User story and test case links**
E.g.: "User story #426 

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity:low"), Type ("UI, "Functional")

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/74168c7f-815b-4a27-b0df-deb3b12d0786)

Done
