### ISSUE TITLE
[Site Setting Page] Incorrect Button Label ('Apply' Instead of 'Save')

### ISSUE THREAD

**Issue by Vadym123456** [ita-social-projects/ZeroWaste#617]
**Environment:** Windows 10 Home, Google Chrome Version 119.0.6045.200 (Official Build) (64-bit)
**Reproducible:** always
**Build found:**

**Preconditions**

1. The user is logged into the system as an Administrator.
2. The 'Site Settings' page is open.

**Steps to reproduce**
1. Verify all button labels

**Actual result**
1. 'Apply' button is on the page

![1](https://github.com/ita-social-projects/ZeroWaste/assets/152202833/01524b4d-189f-46a8-b703-9621ed503ad8)

**Expected result**
1. 'Save' button should be present on the page. (Answer from Oleh Nakonechniy on 04.12.2023)

**User story and test case links**
E.g.: "User story #426

**Labels to be added**
"Bug", Priority ("Low: "), Severity ("Low:"), Type ("UI")

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/7fb565bc-1246-4ef9-957d-d997bd259799)
Done
