### ISSUE TITLE
[Sign up page] Routing error when changing the language version after a failed registration attempt

### ISSUE THREAD

**Issue by obniavko** [ita-social-projects/ZeroWaste#618]
**Steps to reproduce:**
1. Open [Sign up page.](https://zero-waste-staging.onrender.com/en/users/sign_up)
2. Try to sign up with invalid data.
3. Switch to other language verson.

**Expected Result:**
The language version of Sign up page changes.

**Actual Result:**
The button link leads to the non-existent [/users page](https://zero-waste-staging.onrender.com/uk/users) with **No route matches [GET] "/uk/users"** error.

![Redirect](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/72578f49-809f-4a7e-8fbb-4e58e36a5111)

**Comment by Ytrygub** [comment]
https://github.com/ita-social-projects/ZeroWaste/assets/145603083/4bc42e3e-47b8-4e64-951e-6f4758779b2c
