### ISSUE TITLE
[Sign Up Page] Incorrect error message when entering too short password and email

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#620]
Google Chrome Version 119.0.6045.201 (Official Build) (64-bit)
Always reproducible

**Preconditions**: Go to page https://zero-waste-staging.onrender.com/en
**Steps to reproduce**
1. Click on 'Sign Up' tab
2. Fill in email address: 56
3. Fill in Password that consists of 5 characters: 8h
4. Confirm entering the same Password in the field 'Re-password': 8h
5. Fill in First Name and Last Name: /[a-zA-Zа-їА-ЯЄІЇ]+-?'?`?/
6. Choose appropriate country: Ukraine
7. Click 'Sign up' button

**Actual result**
1. An error message 'Password is too short (minimum is 6 characters), Password is too short (minimum is 8 characters), and Password is invalid' appears
2. An error message 'Email is invalid and Email is too short (minimum is 6 characters)' appears

**Expected result**
1. An error message 'Password is too short (minimum is 8 characters)' appears
2. An error message 'Email is too short (minimum is 6 characters)' appears

User story and test case links:
"User story https://github.com/ita-social-projects/ZeroWaste/issues/626
TC # https://jira.softserve.academy/browse/SWQ-466

![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/e42e0fa5-e2d8-4494-94a5-8be7708f85a1)

**Comment by Ytrygub** [comment]
[https://github.com/ita-social-projects/ZeroWaste/issues/646](url)

**Comment by AShoshu** [comment]
![01](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/d608a820-3446-497a-bf14-1f86a32dd49b)
The actual result does not match the expected result.
It is necessary to remove:
1. Email is invalid
2. The password is invalid

Expected result

    An error message 'Password is too short (minimum is 8 characters)' appears
    An error message 'Email is too short (minimum is 6 characters)' appears

**Comment by dafeys** [comment]
Related to https://github.com/ita-social-projects/ZeroWaste/issues/660

Clarification from an expert(20.12.2023): If the field is not empty, it is advisable to show the user all other errors. Because the information entered into the field can be both short and invalid at the same time. The user will be aware of all the following mistakes that have been made

**Comment by AShoshu** [comment]
Clearly understood
