### ISSUE TITLE
[Sign Up page] Incorrectly displayed labels on Sign Up form

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#621]
**Environment:** Google Chrome Version 119.0.6045.201 (Official Build) (64-bit)

**Preconditions**
Page https://zero-waste-staging.onrender.com/en is opened. 

**Steps to reproduce**
1. Go to 'Sign Up' page.

**Actual result**
'Email..' label is described as mandatory field and it is marked with an asterisk. 

**Postconditions**
'Email', 'Password', 'Re-password', 'First Name', 'Last Name' labels should be displayed as mandatory fields with asterisks.
'Email..' label should be displayed correctly as 'Email'.

User story and test case links
"User story https://github.com/ita-social-projects/ZeroWaste/issues/626
TC # 

![Labels on Sign Up page](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/0ecd4c71-0c1f-4699-8e3d-e595d52a2990)

**Comment by fh0enix** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/13628239/7ad56fec-d880-4082-9189-ba318ca3d776)
