### ISSUE TITLE
 "[Admin] Incorrect display of the list of calculator names after opening  'Calculators' page"

### ISSUE THREAD

**Issue by NatLabyk** [ita-social-projects/ZeroWaste#633]
![Out of viewport](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/760b0c24-4ff7-4ef0-b84b-7e8782b5a995)
**Environment:** Windows 11 Home Version 22H2 Build	22621.2506
Chrome Версія 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always,
**Build found:** 

**Preconditions**
1. https://zero-waste-staging.onrender.com/uk is opened in browser
2. User is logged in as admin
3. 'Admin' page is opened

**Steps to reproduce**
1. Click on 'Calculators' tab in header

**Actual result**
List is shifted to the right. 
The width of the table does not adjust to the content and does not adjust to the width of the viewport

**Expected result**
The width of the table have to adjust to the content and  to the width of the viewport

**User story and test case links**
"User story #627 
[Test case](https://jira.softserve.academy/browse/SWQ-453)"

**Labels to be added**
"Bug", Priority ("pri: high "), Severity ("severity: major "), Type ("UI, )

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/2b18f3df-05ac-41a1-8a09-b27f2527b1d3)

Done
