### ISSUE TITLE
 "[Calculators] 'Search' placeholder is not disapeared after placing cursor in 'Search' textfield

### ISSUE THREAD

**Issue by NatLabyk** [ita-social-projects/ZeroWaste#635]
![placeholder](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/51877c38-68d5-4b01-8bdb-0b73cbfb417d)
**Environment:** Windows 11 Home Version 22H2 Build	22621.2506
Chrome Версія 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:**

**Preconditions**
1. https://zero-waste-staging.onrender.com/uk is opened in browser
2. User is logged in as admin
3. 'Admin' page is opened

**Steps to reproduce**
1. Click on 'Calculators' tab
2. Place cursor on 'Search' textfield

**Actual result**
'Search' placeholder is visible in 'Search' textfield

**Expected result**
'Search' placeholder is disappeared in 'Search' textfield

**User story and test case links**
E.g.: "User story #627 
[Test case](https://jira.softserve.academy/browse/SWQ-453)"

**Labels to be added**
![placeholder](https://jira.softserve.academy/browse/SWQ-458)

"Bug", Priority ("pri: low "), Severity ("severity: low"), Type ("UI).

**Comment by dafeys** [comment]
"Search" placeholder disappear after the first characters is entered.

**Comment by NatLabyk** [comment]
Ok. Closed
