### ISSUE TITLE
"[Сalculators] 'Search' button does not performed its functional after clicking on it

### ISSUE THREAD

**Issue by NatLabyk** [ita-social-projects/ZeroWaste#636]
**Environment:** Windows 11 Home Version 22H2 Build	22621.2506
Chrome Версія 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:** 

**Preconditions**
1. https://zero-waste-staging.onrender.com/uk is opened in browser
2. User is logged in as admin
3. 'Admin' page is opened

**Steps to reproduce**

1. Click on 'Calculators' tab in header
2. Place cursor into 'Search' textfield
3. Fill in 'Search' textfield with valid data
4. Click on 'Search' button

**Actual result**
Calculator which was searched is not highlighted

**Expected result**
Calculator which was searched is highlighted

**User story and test case links**
E.g.: "User story #627 
[Test case](https://jira.softserve.academy/browse/SWQ-458)"

**Labels to be added**
"Bug", Priority ("pri:high "), Severity ("severity: major"), Type ("Functional").

**Comment by AShoshu** [comment]
https://github.com/ita-social-projects/ZeroWaste/assets/145554575/c84ef085-7c7b-415b-bb4b-c6f9c77a0528
