### ISSUE TITLE
 [Site Settings Page] The 'Close' button in the confirmation message is unavailable."

### ISSUE THREAD

**Issue by Vadym123456** [ita-social-projects/ZeroWaste#637]
**Environment:** Windows 10 Home, Google Chrome Version 119.0.6045.200 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** N/A

**Preconditions**

1. The user is logged into the system as an Administrator.
2. The 'Site Settings' page is opened.

**Steps to reproduce**

1. Click on the 'Save' button.
2. Click on the 'Close' button represented by an "x" to close the confirmation message.

![1](https://github.com/ita-social-projects/ZeroWaste/assets/152202833/cb6f5a05-0953-4bdc-8b78-f6c41183cd52)

**Actual result**
The close button is non-functional.

**Expected result**
The confirmation window should close upon clicking the 'Close' button.

**User story and test case links**
E.g.: "User story #426 

**Labels to be added**
"Bug", Priority ("Medium: "), Severity ("Medium:"), Type ("Functional"), "API" (for back-end bugs).

**Comment by dafeys** [comment]
Please see the issue #562
