### ISSUE TITLE
[Edit Category Page] Incorrect controller in 'Priority' field

### ISSUE THREAD

**Issue by Oksana-Lysak** [ita-social-projects/ZeroWaste#640]
**Environment:** Google Chrome 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:**

**Preconditions**
1. Site is opened in browser: https://zero-waste-staging.onrender.com/uk
2. User is logged in as Administrator
3. 'Categories' page is opened
4. The category has been created

**Steps to reproduce**
1. Click on the "Edit" icon
2. Explore 'Priority' field

**Actual result**
Priority is implemented as a text field with a spinner
<img width="960" alt="Incorrect controller in 'Priority' field" src="https://github.com/ita-social-projects/ZeroWaste/assets/145996520/a83128e3-8f62-4a3b-91c2-9f8263f0932d">

**Expected result**
Priority is implemented as dropdown

"User story #427 Criteria 3
**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Medium"), Type ("UI")

**Comment by Oksana-Lysak** [comment]
Duplicate

**Comment by Oksana-Lysak** [comment]
Related issues
https://github.com/ita-social-projects/ZeroWaste/issues/592
https://github.com/ita-social-projects/ZeroWaste/issues/640

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/f4e7cb9c-5e03-4829-917e-1d2c872d28eb)
