### ISSUE TITLE
[Add Category Page] Error message is duplicated when creating new Category with more than 30 characters in 'Name' field

### ISSUE THREAD

**Issue by Oksana-Lysak** [ita-social-projects/ZeroWaste#641]
**Environment:** Google Chrome 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:**

**Preconditions**
1. Site is opened in browser: https://zero-waste-staging.onrender.com/uk
2. User is logged in as Administrator
3. 'Categories' page is opened

**Steps to reproduce**
1. Click on 'Add category' button
2. Fill 'Name' field with invalid data (more than 30 characters): "qwertyuЇїй!@#$%67890?№GFDSПФWdf"
3. Select valid data "9" in 'Priority'
4. Click on 'Create' button

**Actual result**
Error message is duplicated
<img width="960" alt="1" src="https://github.com/ita-social-projects/ZeroWaste/assets/145996520/733123ed-90e9-4359-8b99-1e64e223fffc">

**Expected result**
Error message appears below the field

**User story** #427 
**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Low"), Type ("UI")

**Comment by Oksana-Lysak** [comment]
Related issues
https://github.com/ita-social-projects/ZeroWaste/issues/641

https://github.com/ita-social-projects/ZeroWaste/issues/642

https://github.com/ita-social-projects/ZeroWaste/issues/608

**Comment by Oksana-Lysak** [comment]
Related issues
https://github.com/ita-social-projects/ZeroWaste/issues/641

https://github.com/ita-social-projects/ZeroWaste/issues/642

https://github.com/ita-social-projects/ZeroWaste/issues/608

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/f87d6360-33c9-47f0-a31a-d71ecc1d5c9a)
