### ISSUE TITLE
[Add Category Page] Error message is duplicated when creating new Category with less than 3 characters in 'Name' field

### ISSUE THREAD

**Issue by Oksana-Lysak** [ita-social-projects/ZeroWaste#642]
**Environment:** Google Chrome 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:**

**Preconditions**
1. Site is opened in browser: https://zero-waste-staging.onrender.com/uk
2. User is logged in as Administrator
3. 'Categories' page is opened

**Steps to reproduce**
1. Click on 'Add category' button
2. Fill 'Name' field with invalid data (less than 3 characters): "&h"
3. Select valid data "4" in 'Priority'
4. Click on 'Create' button

**Actual result**
Error message is duplicated
<img width="959" alt="1" src="https://github.com/ita-social-projects/ZeroWaste/assets/145996520/53668604-9c96-4997-acbc-01cb2d2d9ade">

**Expected result**
Error message appears below the field

"User story #427  
**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Low"), Type ("UI")

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/bae2092a-cd4a-4099-ba69-487fc2dcbc03)

Done
