### ISSUE TITLE
[Sign Up Page] No error message when entering too long email

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#643]
**Environment:** Windows 10 Pro Google Chrome Version 119.0.6045.201 (Official Build) (64-bit)
**Reproducible:** always

**Preconditions**
1. Site https://zero-waste-staging.onrender.com/en is opened

**Steps to reproduce**
1. Go to 'Sign Up' tab
2. Click on 'Email' field and enter the following data: ytufmdkxdldldhgvfxfdfdfcbvvnfdtdllljlkjfdsdtstsdfdsfdgxfdxfddfxfdfgd6768dfkfkdkldldd@softserve.com
3. Click 'Sign Up' button 

**Actual result**
There is no error message in regards of 'Email' field. The system shows that email is correct and text field is highlighted in green color.

**Expected result**
An error mesasage 'Wrong or Invalid email address. Please correct and try again' appears.

**User story and test case links**
User story #626 
Test case https://jira.softserve.academy/browse/SWQ-462

![Screenshot_8](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/2085d882-41a6-4257-b551-466d7e066e8a)

**Comment by dafeys** [comment]
![image](https://github.com/ita-social-projects/ZeroWaste/assets/36037839/d9dcdab6-9ef8-4dc0-b700-788abf985553)

There is allowed from 6 to 100 characters

**Comment by Ytrygub** [comment]
During developers and Tech Expert meeting there was a solution that restriction of entering characters for Email field is max 100 characters. 
The appropriate error message 'Email is too long (maximum is 100 characters)' is correct.
