### ISSUE TITLE
[Sign Up Page] Incorrect error message when entering too long password 

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#644]
**Environment**: Windows 10 Pro Google Chrome Version 119.0.6045.201 (Official Build) (64-bit)
**Reproducible**: always

**Preconditions**

Site https://zero-waste-staging.onrender.com/en is opened

**Steps to reproduce**

1. Go to 'Sign Up' tab
2. Click on 'Password' field and enter the following data: sdhfosizps4ui58rw469w7s9eufjklxdjclkjvzlkwueioruoiurt834fujsdklxjflzkjlirude4ioisxfjkldjklfjie48o5iurdflk66666666666666kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
3. Click 'Sign Up' button

**Actual result**
An error message 'Password is too long (maximum is 128 characters) and Password is too long (maximum is 64 characters)' appears

**Expected result**
An error message 'Password is too long (maximum is 64 characters)' appears

**User story and test case links**
User story https://github.com/ita-social-projects/ZeroWaste/issues/626
Test case https://jira.softserve.academy/browse/SWQ-462

![Screenshot_9](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/f0e7336d-4b1b-496b-9bff-dac4bbe22f43)

**Comment by Ytrygub** [comment]
[https://github.com/ita-social-projects/ZeroWaste/issues/660](url)
[https://github.com/ita-social-projects/ZeroWaste/issues/646](url)
[https://github.com/ita-social-projects/ZeroWaste/issues/620](url)

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/f529bffe-c8be-4e8f-b0f3-4a156adc11b4)

Done
