### ISSUE TITLE
 "[Calculators] Calculator name longer than 30 characters is created and saved in system after clicking on 'Create button'

### ISSUE THREAD

**Issue by NatLabyk** [ita-social-projects/ZeroWaste#645]
**Environment:** Windows 11 Home Version 22H2 Build	22621.2506
Chrome Версія 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:** 

**Preconditions**
1. https://zero-waste-staging.onrender.com/uk is opened in browser
2. User is logged in as admin
3. 'Admin' page is opened

**Steps to reproduce**
1. Click on 'Calculators' tab in header
2. Click on 'Add calculator' button
3. Fill in 'Name' textfield with invalid value (more than 30 characters)

**Actual result**
Calculator name is created and saved in system.

**Expected result**
'Name' textfield is highlighted in red.
"Name is too long" error message is displayed under 'Name' textfield.

**User story and test case links**
 "User story #627 
[Test case](https://jira.softserve.academy/browse/SWQ-464)"

**Labels to be added**
"Bug", Priority ("pri: high "), Severity ("severity: major"), Type ("Functional")
![Long name](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/c7896dfe-3448-4129-a228-7f2e336a75ad)
.

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/0f9bfd4c-deb4-453c-9068-5582be566e69)

Done
