### ISSUE TITLE
[Users Page] It is not possible to block the user when clicking on the "Ban" button

### ISSUE THREAD

**Issue by AnastasiiaBelik** [ita-social-projects/ZeroWaste#653]
**Environment:** Windows 11 Google Chrome 118.0.5993.118 (Official build) (64-bit) 
**Reproducible:** always
**Build found:**
**Preconditions**

1. User is logged in as Administrator
2. Users page is opened

**Steps to reproduce**
1. Click on the "Bun" button

**Actual result**
1. "Are you sure?" popup appears.
2. The "User Information" page opens

**Expected result**
The user is blocked and removed from the general list of users

https://github.com/ita-social-projects/ZeroWaste/assets/145580448/fb2d1644-b7db-4699-98b0-0cf195623df6

**Comment by Ytrygub** [comment]
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/2da114d3-3ec1-4ad2-b847-a291fbad2602)
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/2020fc49-a7de-41d8-8b73-a9a0160a12cc)
