### ISSUE TITLE
[About Us Page] Incorrect language of text translation

### ISSUE THREAD

**Issue by AShoshu** [ita-social-projects/ZeroWaste#655]
**Environment:** Windows 11.Version 22H2.(64-bit).Firefox 116
**Reproducible:** always
**Build found:*

**Preconditions**
The website https://zero-waste-staging.onrender.com/en is open in the browser

**Steps to reproduce**
1. Click on 'About Us' tab

**Actual result**
The text of the page is translated into Latin

https://github.com/ita-social-projects/ZeroWaste/assets/145554575/06fc6005-c2d9-47ec-9c93-20c388694c2d

**Expected result**
The text of the page is translated into English

**User story and test case links**
E.g.: "User story #

**Comment by NatLabyk** [comment]
Fixed
