### ISSUE TITLE
[Sign Up] Error message when new user is created with valid data

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#662]
**Environment**: Windows 10 Pro Google Chrome Version 119.0.6045.201 (Official Build) (64-bit)
**Reproducible**: always

**Preconditions**
Site https://zero-waste-staging.onrender.com/en is opened

**Steps to reproduce**

1. Go to 'Sign Up' tab
2. Set correct value in 'Email Address' field: olgaprots2@softserve.com
3. Set correct value in 'Password' field: Globus5678%*hy
4. Duplicate the same value in 'Re-password' field: Globus5678%*hy
5. Set correct value in 'First Name' field: Olga
6. Set correct value in 'First Name' field:Prots
7. Click on button 'Sign Up'

**Actual result**
Error message "We're sorry, but something went wrong. If you are the application owner check the logs for more information." appears.

**Expected result**
1. 'Sign Up' page is opened
2. Message notification 'User has been successfully created'

User story and test case links
User story https://github.com/ita-social-projects/ZeroWaste/issues/626
Test case https://jira.softserve.academy/browse/SWQ-471

![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/c1130f5f-8738-4c9d-aee4-ed0a91ccead9)

**Comment by obniavko** [comment]
Можливість реєстрації нових користувачів було прибрано. Переміщено в No status.

**Comment by loqimean** [comment]
closed as not relevant

**Comment by loqimean** [comment]
closed as not relevant
