### ISSUE TITLE
Change the view of the About Us page

### ISSUE THREAD

**Issue by iambrozjak** [ita-social-projects/ZeroWaste#663]
Preconditions
The website https://zero-waste-staging.onrender.com/en is open in the browser
<img width="948" alt="task page about" src="https://github.com/ita-social-projects/ZeroWaste/assets/129009813/d46b23fd-5497-44e7-b916-415cff1b2c60">

Steps to reproduce:

Click on 'About Us' tab
Actual result:
The text of the page is translated into Latin
Expected result:
The text of the page is displayed in English. The styles correspond to the overall style of the project.

**Comment by NatLabyk** [comment]
Fixed

![Image](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/6e3d335a-3bbf-46e0-abcd-2d9f1c4b4a19)

**Comment by NatLabyk** [comment]
Duplicate #655
