### ISSUE TITLE
"[Calculators] Incorrect error message in Ukrainian localization  is  displayed after clicking 'Створити калькулятор' button

### ISSUE THREAD

**Issue by NatLabyk** [ita-social-projects/ZeroWaste#673]
**Environment:** Windows 11 Home Version 22H2 Build 22621.2506
Chrome Версія 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:** 

**Preconditions**
1. https://zero-waste-staging.onrender.com/uk is opened in browser
2. User is logged in as admin
3. 'Admin' page is opened
4. Ukrainian locolization is chosen

**Steps to reproduce**
1.Click on 'Калькулятори' tab in header
2. Click on 'Додати калькулятор' button
3. Fill in 'Назва' textfield with invalid value (1 characters - letter or digit)
**Actual result**
'Одна помилка перешкоджає зберегти калькулятор
Назва is too short' error messages are displayed 

**Expected result**
'Одна помилка перешкоджає зберегти калькулятор
Назва є короткою' error messages are displayed 

**User story and test case links**
E.g.: "User story #627 
[Test case](https://jira.softserve.academy/browse/SWQ-464)"

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity:low"), Type ("UI)
![Ukr local](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/c9121b02-6c3e-4b50-9dcc-032909332fac)

**Comment by Ytrygub** [comment]
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/1d4c68d2-7f85-4960-9c5c-8d374ad3f1a3)
'Назва занадто коротка (мінімум 2 знаки)' error message appears
