### ISSUE TITLE
[Button color] The buttons have a different coloror on  'Categories'_'Calculators'_Site Settings' pages when hovered over with the mouse

### ISSUE THREAD

**Issue by AShoshu** [ita-social-projects/ZeroWaste#675]
**Environment:**Windows 11.Version 22H2.(64-bit).Firefox 116
**Reproducible:** always
**Build found:** 

**Preconditions**

1. User logined in system as Administrator.

**Steps to reproduce**
1. Click on 'Admin' tab
3. Open 'Categories' page
4. Place the mouse cursor on the green buttons
5. Click on 'Setting' page
6. . Place the mouse cursor on the green buttons

**Actual result**
The green buttons have a different shade when the mouse is hovering over them

https://github.com/ita-social-projects/ZeroWaste/assets/145554575/375ecb63-08d8-42d7-b117-3acc965b769e

**Expected result**
All green buttons on the site should have the same color #73952f when the mouse is hovered over 

https://github.com/ita-social-projects/ZeroWaste/assets/145554575/91ed15a0-c4c2-4d93-92d4-898576a5a12b

**Comment by NatLabyk** [comment]
Fixed
