### ISSUE TITLE
[Headers] On the "Users" page, a non-bold underline is applied in the caption of the table headers

### ISSUE THREAD

**Issue by AShoshu** [ita-social-projects/ZeroWaste#681]
**Environment:** Windows 11.Version 22H2.(64-bit).Firefox 116
**Reproducible:** always

**Preconditions**
1. Website https://zero-waste-staging.onrender.com/en is open
2. User logged as administrator

**Steps to reproduce**
1. Click on 'Admin' tab.
2. Click on 'User' page.

**Actual result**
Table column headings are written without bold text.
![Снимок экрана 2023-12-14 162951](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/f13b47c9-7b62-4774-a17b-78db26e62911)

**Expected result**
Table column headings are written using bold text

**Comment by obniavko** [comment]
Done.
