### ISSUE TITLE
[Table background]Incorrect background color in table on "Calculators" page

### ISSUE THREAD

**Issue by AShoshu** [ita-social-projects/ZeroWaste#682]
**Environment:** Windows 11.Version 22H2.(64-bit).Firefox 116
**Reproducible:** always, rarely, sometimes etc.

**Preconditions**

1. Website https://zero-waste-staging.onrender.com/en is open.
2. User logged as administrator

**Steps to reproduce**

1. Click on 'Admin' tab
2. Click on 'User' page.

**Actual result**
Gray background color in the table on the "Calculators" page.
![Снимок экрана 2023-12-14 163151](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/e5905302-f5d4-4f44-b780-49887a760863)

**Expected result**
White background color in the table on the "Calculators" page

**Comment by Ytrygub** [comment]
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/018a33bf-0b27-4543-a67d-8d429468bada)
