### ISSUE TITLE
[Sign Up page] No possibility to sign in when clicking 'Sign In with Google' or 'Sign in with Facebook' links 

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#684]
**Environment:** Windows 10 Pro Google Chrome Version 119.0.6045.201 (Official Build) (64-bit)
**Reproducible:** always

**Preconditions**
Site https://zero-waste-staging.onrender.com/en is opened

**Steps to reproduce**
1. Go to 'Sign Up' tab
2. Click on 'Sign In with Google' link
4. Go back to 'Sign Up' page
5. Click on 'Sign In with Facebook' link

**Actual result**
1. Error message 'Access Denied: Authorization Error' appears when trying to sign in with Google
2. Error message 'Invalid application ID. It looks like the app ID provided is invalid.' appears when trying to sign in with Facebook

**Expected result**
1. User is signed in via Google account
2. User is signed in via Facebook account

**User story and test case links**
"User story (https://github.com/ita-social-projects/ZeroWaste/issues/626)
Test case (https://jira.softserve.academy/browse/SWQ-482)"

![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/4d588fa4-1086-4664-b8cf-2f080cee2310)
![Untitled](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/3ef66b49-bd2f-44e6-a41c-a26dbe626d61)

**Comment by iryna-borniak** [comment]
To fix a Sign In with Google issue, it is necessary to generate OAuth 2.0 credentials in Google Cloud.

**Comment by obniavko** [comment]
Можливість реєстрації нових користувачів та авторизації через соціальні мережі було прибрано. Переміщено в No status.

**Comment by loqimean** [comment]
as we decide, for now, we don't provide ability to sign up
