### ISSUE TITLE
[Add Category Page] The tooltip is not localized

### ISSUE THREAD

**Issue by Oksana-Lysak** [ita-social-projects/ZeroWaste#687]
**Environment:** Google Chrome 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:**

**Preconditions**
1. Site is opened in browser: https://zero-waste-staging.onrender.com/uk
2. The website is presented in Ukrainian
3. User is logged in as Administrator
4. 'Categories' page is opened

**Steps to reproduce**
1. Click on 'Add category' button
2. Hover cursor over the 'Name' field

**Actual result**
Tooltip appears in English

**Expected result**
Tooltip appears in Ukrainian

**User story** #427  
**Labels**
"Bug", Priority ("Low"), Severity ("Low"), Type ("UI")

<img width="958" alt="1" src="https://github.com/ita-social-projects/ZeroWaste/assets/145996520/64938445-c758-482f-81d3-7f412e302ef8">

**Comment by Oksana-Lysak** [comment]
Related issues
https://github.com/ita-social-projects/ZeroWaste/issues/670

**Comment by DmytroStoliaruk** [comment]
Can't reproduce it on the current version of site https://zero-waste-staging.onrender.com/uk
