### ISSUE TITLE
 Not actuall information on page "Contact us"

### ISSUE THREAD

**Issue by iambrozjak** [ita-social-projects/ZeroWaste#690]
Preconditions

https://zero-waste-staging.onrender.com/en is opened in browser
'Contact us' page is opened
Steps to reproduce
1. Click on 'Contact us' in navigation menu
2. Company adress, tel, About us - are not actual information
3. Email adress is not actuall. 
![контакт ас](https://github.com/ita-social-projects/ZeroWaste/assets/129009813/442a838d-5ebb-429d-9720-a83035ce0bea)

Actual result
The page contains information about the company that is not correct or is a stub.
Expected result
The page provides only correct information (email) about the company. The 'About us' button is not needed, since it is placed in the navigation menu.

**Comment by NatLabyk** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/883b6c11-7b33-4219-9ffc-c72832b4925a)



![Image](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/24e2a433-524a-453c-8dc9-3aaffa008f74)

Approved by expert. Fixed
