### ISSUE TITLE
[Calculators Page] Missing output between 'Search' and 'Add Calculator' buttons

### ISSUE THREAD

**Issue by AShoshu** [ita-social-projects/ZeroWaste#694]
**Environment:** Windows 11.Version 22H2.(64-bit).Firefox 116
**Reproducible:** always

**Preconditions**
The user is logged into the system as an administrator.
The "Calculators" tab is open

**Actual result**
Missing output between 'Search' and 'Add Calculator' buttons
![1](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/7dbc6e9d-db51-4db0-9a5d-4cc70eb99ccf)

**Expected result**
There is an indentation between the 'Search' and 'Add Calculator' buttons

**Comment by NatLabyk** [comment]
Fixed

![Image](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/791d9cd8-77d0-4f65-80e7-a65a0ac00032)
