### ISSUE TITLE
[Users/Products/Categories page] Error when clicking on table header

### ISSUE THREAD

**Issue by obniavko** [ita-social-projects/ZeroWaste#705]
**Steps to reproduce:**
1. Open [Users](https://zero-waste-staging.onrender.com/en/account/users)/[Products](https://zero-waste-staging.onrender.com/en/account/products)/[Categories](https://zero-waste-staging.onrender.com/en/account/categories) page.
2. Click on sortable table header.

**Expected Result:**
The items on the page are sorted.

**Actual Result:**
An error occurs.

![table-header](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/e2bbaa48-31dc-41f4-9180-96d4822662d1)

![sorted](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/48401107-8456-41d2-8739-6ccdc0f8169a)

**Comment by Ytrygub** [comment]
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/dfd04cf5-3574-4141-a513-cd1c4db19cda)
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/d821a48d-2492-461a-80c0-4beea60f8d1b)
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/59dbdb3c-bea2-43b0-b9d9-7d97553c393c)
