### ISSUE TITLE
[Add Category Page]  Allowed reserved characters in the 'Name' field

### ISSUE THREAD

**Issue by Oksana-Lysak** [ita-social-projects/ZeroWaste#709]
**Environment:** Google Chrome 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:**

**Preconditions**
1. Site is opened in browser: https://zero-waste-staging.onrender.com/uk
2. User is logged in as Administrator
3. 'Categories' page is opened

**Steps to reproduce**
1. Click on 'Add category' button
2. Fill 'Name' field with invalid data (reserved characters): "&^$#@!!()_=-"
3. Select valid data "10" in 'Priority'
4. Click on 'Create' button

**Actual result**
- Category is created.
![709](https://github.com/ita-social-projects/ZeroWaste/assets/145996520/126a7145-b42c-400d-a337-32ab4f0efd92)

**Expected result**

- "Only letters and numbers are allowed" error message appears below the field.
- Category isn't created.

**User story and test case links**
E.g.: "User story #427 

**Labels to be added**
Type: "Functional"

**Comment by Oksana-Lysak** [comment]
At the meeting on 12/30/2023 with BA Oleh Nakonechniy and Ihor Kohut decided to add to Acceptance Criteria 2:

"The field only allow alphanumeric input"
"Accepts upper and lower case letters".
"Not allow reserved characters".

These changes have been added to the US #427 

https://github.com/orgs/ita-social-projects/projects/25/views/7?filterQuery=598&pane=issue&itemId=46428738

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/3933e938-a7c7-4b56-a4b5-36cd79e4fcea)
