### ISSUE TITLE
[Add Category Page] Wrong error message appears when creating new Category with empty 'Name' field 

### ISSUE THREAD

**Issue by Oksana-Lysak** [ita-social-projects/ZeroWaste#710]
**Environment:** Google Chrome 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:**

**Preconditions**
1. Site is opened in browser: https://zero-waste-staging.onrender.com/uk
2. User is logged in as Administrator
3. 'Categories' page is opened

**Steps to reproduce**
1. Click on 'Add category' button
2. Leave 'Name' field empty
3. Fill in 'Priority' field with valid data: "5"
4. Click on 'Create' button
5. Repeat steps 1-4 for the Ukrainian version of the site.

**Actual result**
1. "Name can't be blank and Name is too short (minimum is 3 characters)" error message appears
![capture_240104_133907](https://github.com/ita-social-projects/ZeroWaste/assets/145996520/bab2459d-26c7-4d98-9e1f-6d03224740f0)

2. "Назва не може бути пустою і Назва занадто коротка (мінімум 3 знаки)" error message appears
![710 1](https://github.com/ita-social-projects/ZeroWaste/assets/145996520/87e0f697-2923-4348-a959-86d7558c4c38)

**Expected result**
1. "Name can't be blank" error message appears
2. "Назва не може бути порожньою" error message appears

**User story and test case links**
"User story #427 

**Labels to be added**
Type ("UI")

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/2befb950-68cb-4859-ae9e-4a23df78333d)
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/46adde2b-5e5a-44ff-a9b7-e988743cd99d)
