### ISSUE TITLE
Warning PaperTrail when server starts

### ISSUE THREAD

**Issue by dafeys** [ita-social-projects/ZeroWaste#711]
**Preconditions**
Pull updates from the develop branch

**Steps to reproduce**
1. Start the server with the command rails s

**Actual result**
Receive a warning:
```
      PaperTrail 12.2.0 is not compatible with ActiveRecord 7.1.2. We allow PT
      contributors to install incompatible versions of ActiveRecord, and this
      warning can be silenced with an environment variable, but this is a bad
      idea for normal use. Please install a compatible version of ActiveRecord
      instead (>= 5.2, < 7.1). Please see the discussion in paper_trail/compatibility.rb
      for details.
```

**Expected result**
There should be no warnings

**Comment by obniavko** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/a0c65abc-3cc7-43b3-86a1-1fcab4258cff)
