### ISSUE TITLE
[Admin] Inconsistent buttons' border radius

### ISSUE THREAD

**Issue by kisiohlova** [ita-social-projects/ZeroWaste#713]
**Steps to reproduce**
1. Go to Admin -> Calculators
2. Go to Admin -> History
3. Go to Admin -> Products
4. Go to Admin -> Categories

**Actual result**
The buttons have 0.375rem (6px) border radius.
1:
![telegram-cloud-photo-size-2-5251526774645445440-y](https://github.com/ita-social-projects/ZeroWaste/assets/64698588/bc4f6488-08bd-4d39-8d10-83e2017fba1e)
2:
![telegram-cloud-photo-size-2-5251526774645445441-m](https://github.com/ita-social-projects/ZeroWaste/assets/64698588/bc5c3521-5022-493b-8e6f-f32376a920a7)
3:
![telegram-cloud-photo-size-2-5251526774645445442-x](https://github.com/ita-social-projects/ZeroWaste/assets/64698588/6bd63d09-5a84-480b-8b74-bde6ff39921a)
4:
![telegram-cloud-photo-size-2-5251526774645445443-x](https://github.com/ita-social-projects/ZeroWaste/assets/64698588/4722e9eb-f72f-475e-be45-6881d997bef8)

**Expected result**
All buttons have the same border radius as the buttons on the main page -- 0.25rem (4px)
<img width="866" alt="image" src="https://github.com/ita-social-projects/ZeroWaste/assets/64698588/e815804a-96a1-42f8-9ae5-c76cc144a851">

**Comment by NatLabyk** [comment]
Fixed
