### ISSUE TITLE
[Admin] Invisible button on App Config page

### ISSUE THREAD

**Issue by kisiohlova** [ita-social-projects/ZeroWaste#714]
**Steps to reproduce**
1. Go to Admin -> App Config

**Actual result**
The Update button isn't visible
<img width="826" alt="image" src="https://github.com/ita-social-projects/ZeroWaste/assets/64698588/f0e96193-0dec-4195-9ae9-cafca7728bf9">

**Expected result**
Visible Update button.

**Comment by NatLabyk** [comment]
Fixed

![Image](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/e01b59e4-5c2a-4aa5-944c-7497aad866ea)



![Image](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/db0fe943-30c7-4106-9168-c2212cf12dec)
