### ISSUE TITLE
[Products] 'Sum' hint isn't translated into Ukrainian when changing the language

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#717]
**Environment:** Windows 10 Pro 22H2 Google Chrome Version 119.0.6045.201 (Official Build) (64-bit)
**Reproducible:** always

**Preconditions**
1. Site https://zero-waste-staging.onrender.com/en is opened.
2. Admin is logged in.

**Steps to reproduce**
1. Go to 'Admin' tab
2. Go to 'Products' section
3. Click 'Add product' button
4. Put ticks on products items below the 'Title' text field.
5. Change the language

**Actual result**
'Sum' hint is not translated into Ukrainian when changing the language.

**Expected result**
When clicking 'Українська' button then 'Сума' must be displayed in every field.

**User story and test case links**
E.g.: "User story #424 
[Test case](https://jira.softserve.academy/browse/SWQ-451)"

https://github.com/ita-social-projects/ZeroWaste/assets/145603083/7e753add-a138-4e45-a41b-c2f2580c7306

**Comment by NatLabyk** [comment]
Fixed

![Image](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/4b0bf8f0-7aa0-4d08-aa70-f42cc8b6f4e3)
