### ISSUE TITLE
 "[Site Setting] 'Favicon' label and 'Choose File' placeholder are in English with Ukrainian localization

### ISSUE THREAD

**Issue by NatLabyk** [ita-social-projects/ZeroWaste#722]
**Environment:** Windows 11 Home Version 22H2 Build	22621.2506
Chrome Версія 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:** 
**Preconditions**
1. Site is opened in browser https://zero-waste-staging.onrender.com/en
2. User is logged in as Admin
3. 'Admin' page is opend
4. Site Setting tab is chosen with Ukrainian localization

**Steps to reproduce**
1. Go to 'Favicon' button 
**Actual result**
'Favicon' label is in English.
'Choose File' button is in English.

**Expected result**
'Favicon' label is in Ukrainian.
'Choose File' button is in Ukrainian

**User story and test case #426
[Test case]
![Знімок екрана 2024-01-09 194409](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/2265d260-64df-4319-ac86-edd69490a8a5)

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity: Low"), Type ("Functional").

**Comment by obniavko** [comment]
[Duplicate](https://github.com/ita-social-projects/ZeroWaste/issues/614). The Favicon [should not be translated](https://uk.wikipedia.org/wiki/Favicon).
