### ISSUE TITLE
[Products] [Add product] The 'Add product' page is not translated automatically and returns back to 'Products' page when invalid symbols are entered

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#723]
**Environment**: Windows 10 Pro 22H2 Google Chrome Version 119.0.6045.201 (Official Build) (64-bit)
**Reproducible**: always

**Preconditions**
1. Site https://zero-waste-staging.onrender.com/en is opened.
2. Admin is logged in.

**Steps to reproduce**
1. Go to 'Admin' tab
2. Go to 'Products' page
3. Click 'Add product' button
4. Enter invalid symbols (for example, ghtyrufhytrdtyuhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh)
5. Click 'Create' button and check if error message 'Title too long (maximum 30 symbols)' appears 
6. Switch the language
7.  Click 'Додати продукт' button
8. Enter invalid symbol (for example, s)
9. Click 'Створити' button and check if error message appears 'Назва занадто коротка (мінімум 2 знаки)'
10. Switch the language

**Actual result**
After switching the language the Admin is returned back to the page with the list of products.

**Expected result**
There is possibility to observe translation when switching the language.

**User story and test case links**
E.g.: "User story #424 
[Test case](https://jira.softserve.academy/browse/SWQ-451)"

https://github.com/ita-social-projects/ZeroWaste/assets/145603083/bd8e4940-af30-4667-b138-ff4b1053aedf

**Comment by NatLabyk** [comment]
Not a defetc
