### ISSUE TITLE
["Edit product" page] Category can't be removed

### ISSUE THREAD

**Issue by obniavko** [ita-social-projects/ZeroWaste#726]
**Steps to reproduce:**
1. Open "Edit product" page.
2. Uncheck category (if present) and save the product.
3. Open "Products" page.

**Expected Result:**
The product is saved with category removed.

**Actual Result:**
The category is not removed from the product properties.

![EditProduct](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/bd22485a-52a8-4d7b-898a-8c612278c597)

**Comment by NatLabyk** [comment]
Fixed

https://github.com/ita-social-projects/ZeroWaste/assets/152202895/2e47d15a-f57b-4e8d-8db7-95bcb1df0efc
