### ISSUE TITLE
["Edit product" page] Incorrect button text

### ISSUE THREAD

**Issue by obniavko** [ita-social-projects/ZeroWaste#727]
**Steps to reproduce:**
1. Open "Edit product" page.

**Expected Result:**
The button has text "Update product".

**Actual Result:**
The button has text "Create".

![Create](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/4bd5019d-27c8-4ab4-adea-ec22a12ab67b)

**Comment by AShoshu** [comment]
![Image](https://github.com/ita-social-projects/ZeroWaste/assets/145554575/b9ab0f5b-89cc-4a09-91a2-874640a532a8)
