### ISSUE TITLE
 "[Products] 'Budget' , 'Medium' checkbox labels have incorrect localization

### ISSUE THREAD

**Issue by NatLabyk** [ita-social-projects/ZeroWaste#728]
**Environment:** Windows 11 Home Version 22H2 Build	22621.2506
Chrome Версія 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:**

**Preconditions**
1. https://zero-waste-staging.onrender.com/en is opened in browser
2. User is logged in as admin
3. 'Admin' page is opened
4. 'Products' tab is chosen
5.  English localization is chosen
**Steps to reproduce**
1. Change localization into Ukrainian

**Actual result**
'Budget', 'Medium', 'Преміум' checkbox labels are displayed in EN local
'Budget', 'Medium', 'Преміум' checkbox labels are displayed in Uk local

**Expected result**
'Budget', 'Medium', 'Premium' checkbox labels are displayed in EN local
'Бюджет', 'Медіум', 'Преміум' checkbox labels are displayed in Uk local

**User story and test case links**
E.g.: "User story #424 
[Test case]
![Знімок екрана 2024-01-11 114536](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/8b60e49d-e97d-4c17-a20d-ba9eb580e2fd)
![Знімок екрана 2024-01-11 120952](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/2ef84db3-a356-4277-8c08-9fc86f463c28)

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: low"), Type ("UI").

**Comment by iambrozjak** [comment]
Budget', 'Medium', 'Premium' labels displayed on this page are created in the categories section. The admin can add categories in the language of his choice. Labels are displayed as they are created in the categories and it is not advisable to translate them.
