### ISSUE TITLE
[Admin/Products] Incorrect titles order

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#731]
**Environment**: Windows 10 Pro 22H2 Google Chrome Version 119.0.6045.201 (Official Build) (64-bit)
**Reproducible**: always

**Preconditions**
1. Site https://zero-waste-staging.onrender.com/en is opened.
2. Admin is logged in.

**Steps to reproduce**
1. Go to 'Admin' tab
2. Go to 'Products' page

**Actual result**
The titles numbers are placed in chaotic order.

**Expected result**
The order of numbers must be consecutive.

User story and test case links
E.g.: "User story https://github.com/ita-social-projects/ZeroWaste/issues/424
[Test case](https://jira.softserve.academy/browse/SWQ-451)"

![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/9fca7c01-bd88-4292-a385-83324bbefa5e)

**Comment by kisiohlova** [comment]
This [PR](https://github.com/ita-social-projects/ZeroWaste/pull/706) fixes the sorting (asc, desc order) by clicking on "#" and "Title".

**Comment by Ytrygub** [comment]
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/0f2cd69a-2790-4a1f-abdf-181287fc7914)
