### ISSUE TITLE
[Log In] Incorrectly displayed labels 

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#734]
**Environment**: Google Chrome Version Version 120.0.6099.217 (Official Build) (64-bit) Windows 10 Pro 22H2 

**Preconditions**
Page https://zero-waste-staging.onrender.com/en is opened.

**Steps to reproduce**

1. Go to 'Log in' page.

**Actual result**
'Email' label is described as mandatory field and it is marked with an asterisk.

**Postconditions**
'Email' and 'Password' labels should be displayed as mandatory fields with asterisks.

User story and test case links
"User story https://github.com/ita-social-projects/ZeroWaste/issues/626
TC #

![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/1f37618b-8da9-4a53-b79e-b7c952afb8dc)

**Comment by NatLabyk** [comment]
Fixed

![Image](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/ba2d960c-37a4-4fa5-a73d-a12c4d060b75)



![Image](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/1f900a81-d67d-480a-b98b-52b6f6244658)
