### ISSUE TITLE
[Add product Page] Product is created with a price and a category if the category checkbox is unchecked

### ISSUE THREAD

**Issue by Oksana-Lysak** [ita-social-projects/ZeroWaste#740]
**Environment:** 
Windows 11 Pro Version 22H2 Build 22621.2428
Google Chrome 118.0.5993.118 (Official build) (64-bit)

**Reproducible:** always
**Build found:**

**Preconditions**
1. Site is opened in browser: https://zero-waste-staging.onrender.com/uk
2. User is logged in as Administrator
3. 'Products' page is opened

**Steps to reproduce**

1. Click 'Add product' button
2. Fill the 'Назва' field with valid data
3. Select the category checkbox
4. Fill the 'Сума' field with valid data
5. Uncheck the category checkbox
6. Click on 'Create' button
7. Check this product in the product list

**Actual result**
Product is created with a price and a category

![Add product Page  Product is created with a price and a category if the category checkbox is unchecked](https://github.com/ita-social-projects/ZeroWaste/assets/145996520/d6fb3749-a6b3-4706-9da1-4a6c15e112e3)

**Expected result**
Product is created without a price and a category

**User story and test case links**
"User story #424

**Comment by Ytrygub** [comment]
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/73a1353a-4176-4425-8691-88c57550edaf)
