### ISSUE TITLE
[Add product Page] Entered data and error messages are duplicated after an unsuccessful attempt to create the product with invalid data in 'Сума' field

### ISSUE THREAD

**Issue by Oksana-Lysak** [ita-social-projects/ZeroWaste#741]
**Environment:** 
Windows 11 Pro Version 22H2 Build 22621.2428
Google Chrome 118.0.5993.118 (Official build) (64-bit)

**Reproducible:** always
**Build found:**

**Preconditions**
1. Site is opened in browser: https://zero-waste-staging.onrender.com/uk
2. User is logged in as Administrator
3. 'Products' page is opened

**Steps to reproduce**

1. Click 'Add product' button
2. Fill the 'Назва' field with invalid data
3. Select the category checkbox
4. Fill the 'Сума' field with invalid data
5. Click on 'Create' button

**Actual result**

1. The chosen category checkbox is unchecked
2. 'Сума' fields are displayed near the categories with the unchecked checkbox
3. 'Сума' field with the entered data is duplicated near the categories with the unchecked checkbox
4. The "Сума мусить бути більше ніж або дорівнювати 0" error message is duplicated near the categories with the unchecked checkbox
![Add product Page  Entered data and error messages are duplicated near the categories with the unchecked checkbox after an unsuccessful attempt to create the product](https://github.com/ita-social-projects/ZeroWaste/assets/145996520/95657a52-2f35-4446-96bf-c659e5a6c0f1)

**Expected result**
1. The checkbox remains on the selected category
2. 'Сума' field with entered data is displayed only near the category with the checked checkbox
3. The "Сума мусить бути більше ніж або дорівнювати 0" error message is displayed only near the category with the checked checkbox

**User story and test case links**
"User story #424

**Comment by Oksana-Lysak** [comment]
Related:
https://github.com/ita-social-projects/ZeroWaste/issues/741
https://github.com/ita-social-projects/ZeroWaste/issues/744
https://github.com/ita-social-projects/ZeroWaste/issues/743
https://github.com/ita-social-projects/ZeroWaste/issues/745

**Comment by Ytrygub** [comment]
https://github.com/ita-social-projects/ZeroWaste/assets/145603083/aca64946-44a8-46cc-bd0b-aff85a7a3c79

Kindly ask you to check the following results:
1. The checkbox is still unchecked after clicking 'Створити продукт' button
2. There is no error message when entered sum is invalid

**Comment by NatLabyk** [comment]
Fixed.
