### ISSUE TITLE
[Add product Page] Entered data is duplicated after an unsuccessful attempt to create the product with invalid data in 'Назва' field

### ISSUE THREAD

**Issue by Oksana-Lysak** [ita-social-projects/ZeroWaste#743]
**Environment:** 
Windows 11 Pro Version 22H2 Build 22621.2428
Google Chrome 118.0.5993.118 (Official build) (64-bit)

**Reproducible:** always
**Build found:**

**Preconditions**
1. Site is opened in browser: https://zero-waste-staging.onrender.com/uk
2. User is logged in as Administrator
3. 'Products' page is opened

**Steps to reproduce**

1. Click 'Add product' button
2. Fill the 'Назва' field with invalid data
3. Select the category checkbox
4. Fill the 'Сума' field with valid data
5. Click on 'Create' button

**Actual result**

1. The chosen category checkbox is unchecked
2. 'Сума' fields are displayed near the categories with the unchecked checkbox
3. 'Сума' field with the entered data is duplicated near the categories with the unchecked checkbox
![2](https://github.com/ita-social-projects/ZeroWaste/assets/145996520/5624cfe3-52fc-4ddc-a746-d664b4ed8fc7)

**Expected result**
1. The checkbox remains on the selected category
2. 'Сума' field with entered data is displayed only near the category with the checked checkbox

**User story and test case links**
"User story #424

**Comment by Oksana-Lysak** [comment]
Related:
https://github.com/ita-social-projects/ZeroWaste/issues/741
https://github.com/ita-social-projects/ZeroWaste/issues/744
https://github.com/ita-social-projects/ZeroWaste/issues/743
https://github.com/ita-social-projects/ZeroWaste/issues/745

**Comment by Ytrygub** [comment]
https://github.com/ita-social-projects/ZeroWaste/assets/145603083/752ce5fc-6d0c-4971-8a32-d058a956daa7

Please be informed that the checkbox is unchecked on the selected category when creating new product

**Comment by NatLabyk** [comment]
Fixed
