### ISSUE TITLE
[Products] [Add product] "+" and "-" signs can be used in the "Sum" fields

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#746]
**Environment**: Windows 10 Pro 22H2 Google Chrome Version 120.0.6099.225 (Official Build) (64-bit)
**Reproducible**: always

**Preconditions**

1. Site https://zero-waste-staging.onrender.com/en is opened.
2. Admin is logged in.

**Steps to reproduce**

1. Go to 'Admin' tab
2. Go to 'Products' page
3. Click 'Add product' button
4. Enter valid 'Title'
5. Enter digit and sign '-' in the 'Sum' field (e.g. '2-')
6. Click 'Create' button and check if the product has been created
7. Repeat steps 3-6 but instead of '-' sign enter '+' (e.g. '3+')

**Actual result**
The products were created with empty fields

**Postconditions**
There shouldn't be an opportunity to enter any of those signs '-' and '+' in 'Sum' fields

User story and test case links
E.g.: "User story https://github.com/ita-social-projects/ZeroWaste/issues/424
[Test case](https://jira.softserve.academy/browse/SWQ-451)"

https://github.com/ita-social-projects/ZeroWaste/assets/145603083/820c35e7-ac7c-4b1b-b416-860c658d7ef4

**Comment by NatLabyk** [comment]
Fixed
