### ISSUE TITLE
As an admin I want to have possibility to change site settings so that I can manage and customize the system

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#752]
**As an admin I want to have possibility to change site settings so that I can manage and customize the system** 

**Description**
Describe feature functionality
Add mockup if needed

### Acceptance Criteria

**Epic link**
E.g.: Epic #100 [Epic](https://jira.softserve.academy/browse/100)

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### Tasks 
1. - [ ] sample task.

**Comment by Ytrygub** [comment]
https://github.com/ita-social-projects/ZeroWaste/issues/426[](url)

**Comment by MaryanaDemtsyukh-SoftServe** [comment]
@Ytrygub please review this user story and add description if it's valid.

**Comment by Ytrygub** [comment]
@MaryanaDemtsyukh-SoftServe Please don't take this User story into consideration. This is a duplicate of US 426
