### ISSUE TITLE
[Categories page] Add a Search Bar

### ISSUE THREAD

**Issue by obniavko** [ita-social-projects/ZeroWaste#764]
**As a** User **I want to** have a Search Bar on "Categories" page **so that** I can search for categories.

### Acceptance Criteria
A "Categories" page should have a Search Bar in order to allow User to search for categories.

![Search](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/0d8b14d9-ac4d-42a5-a294-bab023ac306a)

**Comment by NatLabyk** [comment]
Search bar is added and is functioning
