### ISSUE TITLE
[About us] Different sizes of content containers on page

### ISSUE THREAD

**Issue by NatLabyk** [ita-social-projects/ZeroWaste#779]
![Знімок екрана 2024-02-21 212052](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/01c90f86-2bb2-4650-8ac8-f6f0e438221b)
**Environment:**  Windows 11 Home Version 22H2 Build 22621.2506
Chrome Версія 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always.
**Build found:** 

**Preconditions**
1. https://zero-waste-staging.onrender.com/ is opened in browser

**Steps to reproduce**
1. Go to 'About us' page

**Actual result**
Content containers have different size

**Expected result**
Content containers have different size

**User story and test case links**
E.g.: 

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: low"), Type ("UI).

**Comment by Ytrygub** [comment]
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/4bd9c71d-a696-470b-b437-787fd4e41820)
