### ISSUE TITLE
[Calculators] An empty page opens after error message when changing the language

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#783]
**Environment**: Windows 10 Pro 22H2 Google Chrome Version 120.0.6099.225 (Official Build) (64-bit)
**Reproducible**: always

**Preconditions**
1. Site https://zero-waste-staging.onrender.com/en is opened.
2. Admin is logged in

**Steps to reproduce**
1. Go to 'Admin' tab
2. Open 'Calculators' page
3. Click on 'Edit' icon on any of the calculators
4. Change name in 'Name' field. For example, make it too short or too long 
5. Click 'Update calculator' button
6. After error message appeared click on language button in order to change the language

**Actual result**
An empty page opened

**Postconditions**
The language should be changed on 'Edit' page for Calculators 

**User story and test case links**
E.g.: "User story https://github.com/ita-social-projects/ZeroWaste/issues/627

https://github.com/ita-social-projects/ZeroWaste/assets/145603083/f5e6bc31-a33f-4fb4-b56a-7b53c6b2923d

**Comment by dafeys** [comment]
The error occurs due to "No view template for interactive request"
At present, the implementation of CalculatorsController#show is not required and functionality of calculators is not yet implemented, this is not currently relevant
