### ISSUE TITLE
[Timed out session] Two different warning messages appear

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#789]
**Environment**: Windows 10 Pro 22H2 Google Chrome Version 120.0.6099.225 (Official Build) (64-bit)
**Reproducible**: when session time ends

**Steps to reproduce**

1. Log in as Admin
2. After non-working time check if warning message appears

**Actual result**
Two different warning messages 'true' and 'Час вашої сесії вичерпано. Будь ласка, увійдіть до системи знову' appear

**Postconditions**
One warning message 'Час вашої сесії вичерпано. Будь ласка, увійдіть до системи знову' should appear

User story and test case links
E.g.: "User story 

![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/dad7bbec-09db-4033-b78d-f93e240c25ad)

**Comment by OksanaPyrozhok** [comment]
Fixed
![image](https://github.com/ita-social-projects/ZeroWaste/assets/138609814/3064007f-c119-465e-9bc4-f6c8d8323d69)
