### ISSUE TITLE
[Search bar] Default state is not performed after reloading the page

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#790]
**Environment**: Windows 10 Pro 22H2 Google Chrome Version 120.0.6099.225 (Official Build) (64-bit)
**Reproducible**: always

**Preconditions**
1. Site http://51.44.25.104/en is opened.
2. Admin is logged in.

**Steps to reproduce**
1. Go to 'Admin' tab
2. Open 'Calculators' page (or open any other page where search bar is present)
3. Enter key word in the search bar in order to perform search (e.g. diaper)
4. Click 'Search' button
5. Reload the page in order to return search bar to the default state

**Actual result**
The search bar is not cleared and page is not returned to the default state

**Postconditions**
The search bar should be empty after reloading the page

**User story and test case links**
E.g.: "User story

https://github.com/ita-social-projects/ZeroWaste/assets/145603083/2487af1c-73b6-460b-85a9-82b135712fd2

**Comment by obniavko** [comment]
Після перезавантаження сторінки результатів пошуку оновлюється URL з тими ж параметрами пошуку, тому результати пошуку відображаються знову - це нормальна поведінка. Для повернення до необхідної сторінки можна скористатися пунктами меню. Переміщено в No status.

**Comment by NatLabyk** [comment]
Fixed. 
Added 'Clear/Очистити' button  to ransack form that links user to clear (without any filters) page.
