### ISSUE TITLE
Add Footer to Admin Page.

### ISSUE THREAD

**Issue by Natali-Kotelnitska** [ita-social-projects/ZeroWaste#796]

**Comment by Natali-Kotelnitska** [comment]
## Feature: Add Footer to Admin Page

### Description
Enhance the Admin page by incorporating a footer to improve user experience.

### Use Case
Having a footer ensures a consistent user experience across the Admin page for Admin users.

### Proposed Solution
Implement a footer at the bottom of the Admin page that includes copyright details, the company name, and a link to the relevant page of developer information.

### Priority
Medium

**User story and test case links**
E.g.: "User story #795

**Comment by NatLabyk** [comment]
Done

![Image](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/fd2a50d5-caaf-4cca-be26-be24443aed0f)
