### ISSUE TITLE
[Products] Product page is opened after linking with product ID in URL

### ISSUE THREAD

**Issue by NatLabyk** [ita-social-projects/ZeroWaste#799]
**Environment:** Windows 11 Home Version 22H2 Build	22621.2506
Chrome Версія 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:**"

**Preconditions**
1. http://51.44.25.104/en is opened in browser
2. User is logged in as admin with http://51.44.25.104/en/users/sign_in 
3. 'Admin' page is opened
4. Check test  data # 1 (product ID is not exist in  database) using next script: SELECT id FROM products;

**Steps to reproduce**
1. Go to 'Product' page
2. Fill in URL row with  `http://51.44.25.104/en/account/products/#1`

**Actual result**
Product review page is opened 
![Знімок екрана 2024-02-29 130451](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/4bcd83ab-b5a3-472e-a14a-6a8b564b00a5)

**Expected result**
`404` eror message page is opened

**User story and test case links**
E.g.: "User story 
[Test case]"

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: medium"), Type ("Functional").

**Comment by loqimean** [comment]
comments

https://github.com/ita-social-projects/ZeroWaste/pull/926#pullrequestreview-2414817127

**Comment by loqimean** [comment]
requested changes

https://github.com/ita-social-projects/ZeroWaste/pull/926#pullrequestreview-2425283407

**Comment by NatLabyk** [comment]
Fixed
![Image](https://github.com/user-attachments/assets/8620d5e1-eb04-491b-ad16-07819ce89f94)
