### ISSUE TITLE
[Diaper calculator page] The images have different resolutions and are not aligned

### ISSUE THREAD

**Issue by obniavko** [ita-social-projects/ZeroWaste#803]
**Steps to reproduce:**

Open "Diaper calculator" (with a new design) page.

**Expected Result:**
The icons have the same resolutions and are aligned.

**Actual Result:**
The images have different resolutions and the icons protrude beyond the edges of the circles.

![Icons](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/1e21c441-79d0-4a61-9d46-ebc8ae99f2e2)

**Comment by NatLabyk** [comment]
Fixed
All icons have 108*75 resolution
