### ISSUE TITLE
[Products] Error message doest not appear when creating product with negative value

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#804]
**Environment:** Windows 10 Pro 22H2 Google Chrome Version 120.0.6099.225 (Official Build) (64-bit)
**Reproducible:** always

**Preconditions**
1. Site https://zero-waste-staging.onrender.com/en is opened.
2. Admin is logged in

**Steps to reproduce**
1. Go to 'Products' page
2. Click 'Add product' button
3. Enter valid title in 'Title' field
4. Put a tick in 'Sum' checkbox
5. Enter negative value in the 'Sum' field (e.g. -23)
6. Click 'Create product' button

**Actual result**
Error message does not appear and product is not created

**Expected result**
Error message 'Sum must be greater than or equal to 0' or 'Сума мусить бути більше ніж або дорівнювати 0' should appear and product is not created

**User story and test case links**
E.g.: "User story #424 
[Test case](https://jira.softserve.academy/browse/100](https://jira.softserve.academy/browse/ZER-211)"

https://github.com/ita-social-projects/ZeroWaste/assets/145603083/9d0eda80-0763-4b0c-8c40-3ee81b61e956

**Comment by OksanaPyrozhok** [comment]
Fixed, done
![image](https://github.com/ita-social-projects/ZeroWaste/assets/138609814/7907d6ae-6d2e-4003-9e53-f89d2d39356e)
