### ISSUE TITLE
[History] 'Back' button directs to Users page

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#809]
**Environment:** Windows 10 Pro 22H2 Google Chrome Version 120.0.6099.225 (Official Build) (64-bit)
**Reproducible:** always

**Preconditions**
1. Site https://zero-waste-staging.onrender.com/en is opened.
2. Admin is logged in

**Steps to reproduce**
1. Go to 'History' page
2. Scroll down the page
3. Click 'Back' button

**Actual result**
'Back' button directs to Users page

**Postconditions**
1. Instead of 'Back' button 'Up' button should be created
2. 'Up' button should turn the page up

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

https://github.com/ita-social-projects/ZeroWaste/assets/145603083/a39389ab-4335-4e59-8948-cbe38ace2228

**Comment by NatLabyk** [comment]
Issue is solved by creating pagination on the page. 'Back' button is taken away
