### ISSUE TITLE
[Main page] Header is not centered

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#814]
**Environment:** Windows 10 Pro 22H2 Google Chrome Version 120.0.6099.225 (Official Build) (64-bit)
**Reproducible:** always

**Steps to reproduce**
1. Go to site https://zero-waste-staging.onrender.com/en

**Actual result**
Header is not centered on main page

**Expected result**
Header should be centered relative to the main page

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/0b5099b7-a7b4-44f8-af0d-ec4027762771)

**Comment by NatLabyk** [comment]
Сorner elements are aligned with the edge of the header

![Image](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/2e1df4e3-77a2-413a-ab85-e30f30f33243)



![Image](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/77000d77-5067-4bce-a561-6647ccd970dc)
