### ISSUE TITLE
[Users] Dashboard download button is not generating a CSV file with users information

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#818]
**Environment:** Windows 10 Pro 22H2 Google Chrome Version 122.0.6261.112 (Official Build) (64-bit)
**Reproducible:** always

**Preconditions**
1. Site https://zero-waste-staging.onrender.com/en is opened.
2. Admin is logged in

**Steps to reproduce**
1. Go to 'Users' page
2. Click on 'Dashboard' download button

**Actual result**
A warning message 'We're sorry, but something went wrong. If you are the application owner check the logs for more information.' appears

**Expected result**
The download button should generate a CSV file with a list of information about all users

**User story and test case links**
E.g.: "User story #629 
[Test case](https://jira.softserve.academy/browse/100)"

https://github.com/ita-social-projects/ZeroWaste/assets/145603083/7fc0fa4d-aa44-458d-9f51-bbbf96a5e9a4

**Comment by obniavko** [comment]
Bug was fixed.
![CSV](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/9a1b2edf-c829-4ac3-a315-14ff0d358dd6)
