### ISSUE TITLE
[Calculators/Edit page] Admin user has possibility to edit slug in 'Slug' text field

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#822]
**Environment:** Windows 10 Pro 22H2 Google Chrome Version 122.0.6261.112 (Official Build) (64-bit)
**Reproducible:** always

**Preconditions**
1. Site https://zero-waste-staging.onrender.com/en is opened.
2. Admin is logged in

**Steps to reproduce**
1. Go to 'Calculators' page
2. Click on 'Edit' icon
4. Enter some value in 'Slug' text field
5. Click 'Update calculator' button

**Actual result**
Slug has been changed and updated

**Postconditions**
The ability to edit the slug by the Admin user should be removed as the slug is created once together with the calculator and shouldn't be changed after that

**User story and test case links**
E.g.: "User story #627
[Test case](https://jira.softserve.academy/browse/100)"

https://github.com/ita-social-projects/ZeroWaste/assets/145603083/b8b58c1d-086b-4364-b5d1-36e4f3f85e55

**Comment by Ytrygub** [comment]
This issue has been raised according to the directions from technical expert

**Comment by OksanaPyrozhok** [comment]
Done, fixed
