### ISSUE TITLE
[Calculators] Numeric Sequence for duplicate slugs is used with long combinations

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#823]
**Environment:** Windows 10 Pro 22H2 Google Chrome Version 122.0.6261.112 (Official Build) (64-bit)
**Reproducible:** always

**Preconditions**
1. Site https://zero-waste-staging.onrender.com/en is opened.
2. Admin is logged in

**Steps to reproduce**
1. Go to 'Calculators' page
2. Click on 'Add calculator' button
3. Enter calculator name (e.g. Post) in 'Name' text field
4. Click 'Create calculator' button
5. Repeat step 2
6. Enter calculator name (e.g. Пост) in 'Name' text field
7. Repeat step 4

**Actual result**
There were created two calculators with one slug that was created with correct slug name. 
And the second one that had too long combination of numbers 
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/ae45c3aa-1bbd-4e40-9017-07dcb082bcd9)

**Postconditions**
Numeric Sequence for Duplicate Slugs should be used automatically. 
A short number at the end of the slag should be added, which will be +1 more than the previous one (increment).

According to the above example, the slugs should look like the following:
1. Post
2. Post-1 (not post-6dacbe1a-ce2d-41b8-a835-e6838c22b8d1).

In case of creating slugs with numbers, for example 'Post-1' and Пост-1' the slugs should look like the following: 
1. 'Post-1'
2. 'Post-1-1'

**User story and test case links**
E.g.: "User story #627 
[Test case](https://jira.softserve.academy/browse/100)"

**Comment by OksanaPyrozhok** [comment]
Done
