### ISSUE TITLE
[Contact us] Different sizes of content containers on page

### ISSUE THREAD

**Issue by NatLabyk** [ita-social-projects/ZeroWaste#825]
**Environment:**Windows 11 Home Version 22H2 Build	22621.2506
Chrome Версія 118.0.5993.118 (Official build) (64-bit)

**Reproducible:** always
**Build found:** 

**Preconditions**
1. https://zero-waste-staging.onrender.com/ is opened in browser

**Steps to reproduce**
1. Go to 'Contact us' page

**Actual result**
Content containers have different size
![Знімок екрана 2024-03-14 080325](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/3471cdfd-a51d-4c7b-af95-0ec887bbffee)

**Expected result**
Content containers have the same size

**User story and test case links**
E.g.: "User story #
[Test case](https://jira.softserve.academy/browse/ZER-273)

**Labels to be added**
"Bug", Priority ("pri:low "), Severity ("severity:low"), Type ("UI").

**Comment by Ytrygub** [comment]
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/284710fc-0304-4859-9d01-11371fc85d07)
