### ISSUE TITLE
[Contact us] Facebook, Youtube, Instagram icon are missed on 'Contact Us' page

### ISSUE THREAD

**Issue by NatLabyk** [ita-social-projects/ZeroWaste#829]
**Environment:** Windows 11 Home Version 22H2 Build	22621.2506
Chrome Версія 118.0.5993.118 (Official build) (64-bit)

**Reproducible:** always
**Build found:**

**Preconditions**
1. https://zero-waste-staging.onrender.com/ is opened in browser

**Steps to reproduce**
1. Go to 'Contact Us' page 

**Actual result**
Facebook, Youtube, Instagram icons are missed
![Знімок екрана 2024-03-15 164216](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/d72bdca8-b19b-4313-923c-0e9ee73283c6)
**Expected result**
Facebook, Youtube, Instagram icons are present on 'Contact Us' page

**User story and test case links**
 "User story #827
[Test case] "

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: low"), Type ("Functional").

**Comment by Ytrygub** [comment]
https://github.com/ita-social-projects/ZeroWaste/assets/145603083/de4f050b-0198-40f1-927c-bdee8b7c6448
