### ISSUE TITLE
[Calculator] Time of transition is different when hovering over 'Calculate' and 'How to use less' buttons

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#833]
**Environment:** Windows 10 Pro 22H2 Google Chrome Version 122.0.6261.112 (Official Build) (64-bit)
**Reproducible:** always

**Preconditions**
1. Site https://zero-waste-staging.onrender.com/en is opened.

**Steps to reproduce**
1. Click '**Let's go'** button on the main page
2. Hover over '**Calculate**' green button
3. Hover over '**How to use less**' green button

**Actual result**
1. '**Calculate**' button changes its color from green to dark green in 0.5 sec 
2. '**How to use less**' button changes its color from green to dark green instantly

**Expected result**
Both '**Calculate**' and '**How to use less'** buttons should have the same time of transition 0.5 sec when hovering over

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

https://github.com/ita-social-projects/ZeroWaste/assets/145603083/76458caa-e4d0-4d09-b2c4-55ee8838c258

**Comment by NatLabyk** [comment]
Fixed
