### ISSUE TITLE
[Calculator] Word 'Підгузків' is displayed in Ukrainian localization 

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#834]
**Environment:** Windows 10 Pro 22H2 Google Chrome Version 122.0.6261.112 (Official Build) (64-bit)
**Reproducible:** always

**Preconditions**
1. Site https://zero-waste-staging.onrender.com/uk is opened.

**Steps to reproduce**
1. Click '**Почати**' button on the main page
2. Choose in the section 'Вік дитини' parameters - **0 p. 1 міс.**
3. Click '**Розрахувати**' button
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/39e6cacc-6651-4ce6-8f3f-47b1dc1ead9a)

4. Choose in the section 'Вік дитини' parameters - **2 p. 6 міс.**
5. Click '**Розрахувати**' button
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/e4d0b5ad-671c-412e-bea7-18434940414e)

6. Choose in the section 'Вік дитини' parameters - **2 p. 5 міс.**
7. Click '**Розрахувати**' button
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/3cb7753f-0818-4a8c-9349-fba558fff8b2)

**Actual result**
 Word 'Підгузків' should not be present on the page.

**Expected result**
Word 'Підгузків' is present on the page.

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Comment by OksanaPyrozhok** [comment]
Done
Fixed
![2024-04-22 172106](https://github.com/ita-social-projects/ZeroWaste/assets/138609814/ea19c121-e4e8-4c47-ad12-60c0df7db1cb)
