### ISSUE TITLE
[Main page] 'Sign up', 'Log in', 'Log out', 'Admin' tabs are available for user 

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#837]
**Environment:** Windows 10 Pro 22H2 Google Chrome Version 122.0.6261.112 (Official Build) (64-bit)
**Reproducible:** always

**Preconditions**
1. Site https://zero-waste-staging.onrender.com/uk is opened

**Steps to reproduce**
1. Go to 'Log in' tab
2. Ener credentials and log in as admin

**Actual result**
'Sign up', 'Log in' tabs are available for user.
'Log out', 'Admin' tabs are available when user is logged in as admin.

**Expected result**
'Sign up', 'Log in', 'Log out', 'Admin' tabs shouldn't be available for user. 
Admin must have possibility to enter admin tab via the following link https://zero-waste-staging.onrender.com/en/users/sign_in and enter the credentials

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

https://github.com/ita-social-projects/ZeroWaste/assets/145603083/29d9ae80-eeb7-4afc-8e96-77fe4c97861d

**Comment by Ytrygub** [comment]
The issue creation has been agreed with technical expert

**Comment by NatLabyk** [comment]
Extra container "Or continue with" is on pade. Must be deleted

![Image](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/dfb63da3-5d44-4c82-a466-8368c0cbf646)

**Comment by NatLabyk** [comment]
Fixed

![Image](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/123a748b-30a8-4bb2-b935-771c8053b64f)
