### ISSUE TITLE
[Log In] Styles refactoring

### ISSUE THREAD

**Issue by Ytrygub** [ita-social-projects/ZeroWaste#839]
**Environment:** Windows 10 Pro 22H2 Google Chrome Version 122.0.6261.112 (Official Build) (64-bit)
**Reproducible:** always

**Preconditions**
1. Site https://zero-waste-staging.onrender.com/uk is opened

**Steps to reproduce**
1. Go to 'Log In' tab

**Actual result**
1. Heading has small size
2. Placeholder is missed in the textfields
3. 'Sign Up' link is present 
4. Space is different in regards 'Увійти/Log In' button
![image](https://github.com/ita-social-projects/ZeroWaste/assets/145603083/4b3a38ce-fa2b-4b37-8e3f-eb937770763c)

**Expected result**
1. Heading should have size h1
2. Placeholder should be added into the textfields
3. 'Sign Up' link should be removed from the page
4. Space should be similar in regards 'Увійти/Log In' button

**User story and test case links**
"User story #838 
[Test case](https://jira.softserve.academy/browse/ZER-279)"

**Comment by Ytrygub** [comment]
The issue creation has been agreed with technical expert

**Comment by NatLabyk** [comment]
Done
