### ISSUE TITLE
[Contact Us] Label name on 'Send' button becomes darker after hovering over with pointer

### ISSUE THREAD

**Issue by NatLabyk** [ita-social-projects/ZeroWaste#859]
**Environment:** Windows 11 Home Version 22H2 Build	22621.2506
Chrome Версія 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always.
**Build found:** 

**Preconditions**
Site https://zero-waste-staging.onrender.com/en is opened

**Steps to reproduce**

1. Go to 'Contact Us' page
2. Hover over 'Log In' button with pointer

**Actual result**
 'Send' label on button becomes darker

**Expected result**
'Send' label on button doesn`t change brightness

**User story and test case links**
User story #827 
[Test case]

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: low"), Type ("UI")

https://github.com/ita-social-projects/ZeroWaste/assets/152202895/ece00bed-8a5d-41d9-be06-4ca84b38a62c

.

**Comment by NatLabyk** [comment]
Related
#857 
#858

**Comment by OksanaPyrozhok** [comment]
Done
Fixed

Uploading Contact Us _ ZeroWaste - Google Chrome 2024-04-22 17-29-34.mp4…
