### ISSUE TITLE
[+Add calculator] Incorrect error message after creating too short calculator name 

### ISSUE THREAD

**Issue by NatLabyk** [ita-social-projects/ZeroWaste#864]
**Environment:** Windows 11 Home Version 22H2 Build	22621.2506
Chrome Версія 118.0.5993.118 (Official build) (64-bit).
**Reproducible:** always
**Build found:**

**Preconditions**

1. Site https://zero-waste-staging.onrender.com/en is opened.
2. Admin is logged in
3. 'Calculators' page is opend on Admin dashboard

**Steps to reproduce**
1. Click on '+Add calculator'
2. Fill in 'Name' field with value shoter than 2 characters (e.g. "d")
3. Click on 'Create calculator' button 

**Actual result**
'Name is too short' error nessage with red  is displayed under 'Name' field
![Знімок екрана 2024-04-10 104009](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/cef25b69-44c1-497a-b60b-b94a7b3c9311)

**Expected result**
‘Name is too short (minimum is 2 characters)’ error message with red  is displayed under 'Name' field

**Postconditions**
"Check created item is not saved in database using SQL query:
SELECT *FROM calculators
WHERE name =<testdata#1>;"

**User story and test case links**
User story #627
[Test case] (https://zerowasteproject.zebrunner.com/projects/DEF/test-runs/1?caseId=3)

**Labels to be added**
"Bug", Priority ("pri: low "), Severity ("severity: low "), Type ("UI").

**Comment by OksanaPyrozhok** [comment]
Done
Fixed
![image 2024-04-22 175401](https://github.com/ita-social-projects/ZeroWaste/assets/138609814/f1ffc597-17fb-4e21-88e9-265a96a39a0a)
