### ISSUE TITLE
[Add calculator] Incorrect error message after creating calculator name with reserved characters

### ISSUE THREAD

**Issue by NatLabyk** [ita-social-projects/ZeroWaste#865]
**Environment:** Windows 11 Home Version 22H2 Build	22621.2506
Chrome Версія 118.0.5993.118 (Official build) (64-bit)
**Reproducible:** always
**Build found:** 

**Preconditions**

1. Site https://zero-waste-staging.onrender.com/en is opened.
2. Admin is logged in
3. 'Calculators' page is opend on Admin dashboard

**Steps to reproduce**

1. Click on '+Add calculator'
2. Fill in 'Name' field with 2-30 reserved characters  (e.g. "\*/+++--/\*")
3. Click on 'Create calculator' button

**Actual result**
'Name is invalid' error message with red is displayed under 'Name' field
![Знімок екрана 2024-04-10 104123](https://github.com/ita-social-projects/ZeroWaste/assets/152202895/1a47cea8-c645-444b-b462-0a2669b1f1fe)

**Expected result**
'Name contains invalid characters' error message with red is displayed under 'Name' field

**Postconditions**
"Check created item is not saved in database using SQL query:
SELECT *FROM calculators
WHERE name ='\*/+++--/\*';"
**User story and test case links**
User story #627 
[Test case][DEF-3](https://zerowasteproject.zebrunner.com/projects/DEF/test-cases?caseId=3)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by NatLabyk** [comment]
Related with #864

**Comment by OksanaPyrozhok** [comment]
Done
Fixed
![2024-04-22 180001](https://github.com/ita-social-projects/ZeroWaste/assets/138609814/2bf5cc55-5fb3-478b-8e36-e4b4ff90451e)
