### ISSUE TITLE
[Price category] Price categories on the diaper calculator page are not translated into English localization

### ISSUE THREAD

**Issue by OksanaPyrozhok** [ita-social-projects/ZeroWaste#879]
**Environment:** Windows 10, 64-bit
Opera One (101.0.4843.43)
**Reproducible:** always

Preconditions
1. Site https://zero-waste-staging.onrender.com/uk is opened.
2. Admin is logged in.

**Steps to reproduce**
1. Open Diaper calculator page
2. Click on 'English' button localization
3. Choose first category or second.

**Actual result**
On the diaper calculator page, the price categories are displayed in Ukrainian: Бюджетна, Середня, Преміум in the drop-down list

https://github.com/ita-social-projects/ZeroWaste/assets/138609814/cd6d33ad-7882-435a-821c-aca781b76b70

**Expected result**
On the diaper calculator page, the price categories should be named Economy, Average, Premium in the English localization of the drop-down list.

**User story and test case links**
E.g.: "User story #427 

**Labels to be added**
"Bug", Priority ("pri: "hight), Severity ("severity:"medium), Type ("Localization")

**Comment by NatLabyk** [comment]
Fixed
