### ISSUE TITLE
[Header] Header should have the same width as main container

### ISSUE THREAD

**Issue by DmytroStoliaruk** [ita-social-projects/ZeroWaste#884]
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev

**Preconditions**
1. Site https://zero-waste-staging.onrender.com/uk is opened.
2. Go to http://localhost:3000/en/calculator

**Steps to reproduce**
1. Go to http://localhost:3000/en/calculator

**Actual result**

<img width="1489" alt="Screenshot 2024-06-03 at 20 13 22" src="https://github.com/ita-social-projects/ZeroWaste/assets/35365419/4b9eaf39-bd6d-4203-96e4-99a0cd5b264f">

**Expected result**
Header should have the same width as main container

**Labels to be added**
"Bug", Priority ("pri: "hight), Severity ("severity:"medium)

**Comment by NatLabyk** [comment]
Done

![Image](https://github.com/user-attachments/assets/d357c509-d29f-492d-91d8-a15f0f6cbe6d)
