### ISSUE TITLE
Add Breadcrumbs to the Application

### ISSUE THREAD

**Issue by dafeys** [ita-social-projects/ZeroWaste#892]
### DevTask: Add Breadcrumbs to the Application

**Objective:**
Implement a breadcrumb navigation system across the application to improve user navigation and enhance the overall user experience.

**Details:**
- suitable gem for breadcrumbs `breadcrumbs_on_rails`
- breadcrumbs should be added to all main views
- the design should be elegant and match the overall design theme of the site
- breadcrumbs should reflect the current page hierarchy accurately
- write tests to ensure breadcrumbs are displayed correctly

**Comment by NatLabyk** [comment]
Done.
Breadcrumb navigation system is implemented across the application
