### ISSUE TITLE
Create 'Under Construction' Page

### ISSUE THREAD

**Issue by Natali-Kotelnitska** [ita-social-projects/ZeroWaste#896]
### DevTask: Create 'Under Construction' Page

**Objective:** 
Implement an 'Under Construction' page to inform users that certain features are not yet available and integrate this page with the Calculators page to enhance user communication and experience.

**Description:**
***Main Task Details:***

 **1.  Create 'Under Construction' Page:**
- Develop a new view named under_construction.html.erb.
- The design should be elegant and match the overall design theme of the site.
- Include an appropriate image to visually represent the 'under construction' status.
- Implement responsive and visually appealing styles for the message and image.

***Additional Task Details:***

 **2. Integrate 'Under Construction' Page with Calculators Page:**
- Modify the index action in CalculatorsController to render the 'Under Construction' page only in the production environment.

### Acceptance Criteria
- The 'Under Construction' page is created with appropriate styling.
- The page is rendered only in the production environment for the Calculators page index action.

**Comment by NatLabyk** [comment]
Done
https://docs.google.com/spreadsheets/d/1sujH4lmu4MjIP51k3ce_dvXDhQUZCx49H9asfORmCJs/edit?gid=1343828361#gid=1343828361&range=A1:D10
