### ISSUE TITLE
[Diaper calculator] Automatiс scroll down after clicking "calculate"

### ISSUE THREAD

**Issue by lkshkmia** [ita-social-projects/ZeroWaste#906]
**Environment:** Windows 11, zoom to 100%
**Reproducible:** always

**Preconditions**
1. https://zerowastelviv.org.ua/ is opened
2. User has zoom > 80%

**Steps to reproduce**
1. Go to 'Діяльність' on the main page.
2. Click on 'Проєкти' page.
3. Scroll down to 'Калькулятор підгузків'.
4. Click on "Дізнатись більше" button and "Перейти до калькулятора" button.
5. Click on "Почати" button.
6. Enter inormation about child
7. Click "calculate"

**Actual result**
1. When user click "calculate" he doesn't see that the calculations are ready.

![image](https://github.com/user-attachments/assets/605e19fc-9de6-45b2-9bf9-1c6bcb4f4330)

**Expected result**
When the user clicks to calculate, the page automatically scrolls down to calculations:

![image](https://github.com/user-attachments/assets/307622f3-1a78-4894-a004-63063e391a65)

**Labels to be added**
"Bug", Priority ("pri:medium "), Severity ("severity:medium"), Type ("Ul")

**Comment by loqimean** [comment]
comment & approved

https://github.com/ita-social-projects/ZeroWaste/pull/919#pullrequestreview-2414848640

**Comment by NatLabyk** [comment]
Fixed
