### ISSUE TITLE
Update seeds.rb with data for categories

### ISSUE THREAD

**Issue by alexy78** [ita-social-projects/ZeroWaste#920]

**Comment by loqimean** [comment]
request changes

https://github.com/ita-social-projects/ZeroWaste/pull/923#pullrequestreview-2412610984

**Comment by loqimean** [comment]
requested changes
https://github.com/ita-social-projects/ZeroWaste/pull/923#pullrequestreview-2425280156

**Comment by loqimean** [comment]
approved

https://github.com/ita-social-projects/ZeroWaste/pull/923#pullrequestreview-2462223278

**Comment by NatLabyk** [comment]
Data for categories is updated
