### ISSUE TITLE
[Users Dashboard] Admin can lock himself from the app

### ISSUE THREAD

**Issue by DanielVajnagi** [ita-social-projects/ZeroWaste#931]
**Environment:** Windows 10
**Reproducible:** always
**Build found:** develop

**Preconditions**
1. Site https://zero-waste-staging.onrender.com/en is opened.
2. Admin is logged in
3. 'Users' page is opened on Admin dashboard

**Steps to reproduce**
1. Click on 'lock icon' on the user you currently logged in
2. Confirm action

**Actual result**
User locked himself from the app

**Expected result**
User cannot block himself

https://github.com/user-attachments/assets/eeb2743e-2d11-4020-be3e-9a4634ea6418

**Comment by loqimean** [comment]
requested changes

https://github.com/ita-social-projects/ZeroWaste/pull/937#pullrequestreview-2414835615

**Comment by loqimean** [comment]
approved

https://github.com/ita-social-projects/ZeroWaste/pull/937#pullrequestreview-2425283228
